- .size-snapshot.json
- src/Provider.ts
- src/atom.ts
- src/useAtom.ts
- tests/test.tsx
Previously atom value can be `null` with async read atom. This should improve it.
> improve suspense behavior for async read atom

- readme.md
The documents have a beautiful image with some texts explaining more about the library, but we must not forget the screen readers, so I added an alternative text for it.
More: https://www.a11yproject.com/posts/2013-01-14-alt-text/
> Fix imagem alt in readme

- examples/src/style.css
The page selection is disabled for all elements, so the user does not select the code.
Is there any reason for that?
> chore: remove disable selection in demo

- .eslintrc.json
- .size-snapshot.json
- package.json
- rollup.config.js
- src/Provider.ts
- src/useAtom.ts
- src/utils.ts
- tsconfig.json
- yarn.lock
ref: #26 
This adds new `utils` bundle, that is separated from core.
```js
import { atom, useAtom } from 'jotai'
import { useUpdateAtom } from 'jotai/utils'
const countAtom = atom(0)
const Counter = () => {
const [count] = useAtom(countAtom)
return <div>count: {count}</div>
}
const Controls = () => {
const setCount = useUpdateAtom(countAtom)
const inc = () => setCount(c => c + 1)
return <button onClick={inc}>+1</button>
}
```
> utils bundle and use update atom

- .size-snapshot.json
- docs/utils.md
- src/utils.ts
Close #38 
```js
import { atomWithReducer } from 'jotai/utils'
const countReducer = (prev, action) => {
if (action.type === 'inc') {
return prev + 1
} else if (action.type === 'dec') {
return prev - 1
} else {
throw new Error('unknown action type')
}
}
const countReducerAtom = atomWithReducer(0, countReducer)
```
https://codesandbox.io/s/react-typescript-forked-g3tsx
```js
import { atom } from 'jotai'
import { useReducerAtom } from 'jotai/utils'
const countAtom = atom(0)
const [count, dispatch] = useReducerAtom(countAtom, countReducer)
```
https://codesandbox.io/s/react-typescript-forked-eg0mw
> reducer related utils

- .size-snapshot.json
- src/atom.ts
- src/types.ts
- tests/basic.test.tsx
so that we can easily use it for Array.map.
> add atom key on creation

- .size-snapshot.json
- docs/utils.md
- src/utils.ts
Close #23 
```js
import { atomFamily } from 'jotai/utils'
const todoFamily = atomFamily((name) => name)
todoFamily('foo')
// this will create a new atom('foo'), or return the one if already created
```
```js
import { atomFamily } from 'jotai/utils'
const todoFamily = atomFamily(
(name) => (get) => get(todosAtom)[name],
(name) => (get, set, arg) => {
const prev = get(todosAtom)
return { ...prev, [name]: { ...prev[name], ...arg } }
}
)
```
```js
import { atomFamily } from 'jotai/utils'
const todoFamily = atomFamily(
({ id, name }) => ({ name }),
null,
(a, b) => a.id === b.id
)
```
> atom family util

- .size-snapshot.json
- src/Provider.ts
- src/useAtom.ts
Although still not 100% sure what is best to deal with write promise (and Suspense behavior), this should behave more correctly because it doesn't mix read promise and write promise.
It's a bit unfortunate that the bundle size gets bigger.
> separate write promise

- package.json
- yarn.lock
https://github.com/pmndrs/jotai/issues/15#issuecomment-702640632
It was quite surprising to me that my mistake in the upstream package results in breaking all codesandboxes.
This will lock the dependency version, so it won't happen again.
> update dependency and fix its version

- .size-snapshot.json
- package.json
- src/Provider.ts
- tests/basic.test.tsx
- tests/dependency.test.tsx
- yarn.lock
The whole point of v0.8.0 was updating to use-context-selector v1.2, but I forgot to apply this change to use useContextUpdate. I also found a bug in use-context-selector v1.2 which is fixed.
> useContextUpdate in use-context-selector v1.2

- src/atom.ts
- src/utils.ts
We used to distinguish async-read and normal read for certain reason, but it seems we no longer need it.
> simplify async read atom types

- tests/utils/atomWithReducer.test.tsx
I was just thinking, is there any reason there is no reducer-without-argument function signature for this one.
The specific one I'm thinking about is:
```typescript
export function atomWithReducer<Value, Action>(
initialValue: Value,
reducer: (v: Value) => Value
): WritableAtom<Value, undefined>
``` 
(Or similar)
> add atomWithReducer.test

- .size-snapshot.json
- docs/core.md
- src/core/Provider.ts
- src/core/useAtom.ts
- tests/basic.test.tsx
This is a non trivial rewrite in core:
- `dependents` are now in provider state, which should be better for CM
- Provider debug value shows `deps(=dependens)`, which allows easier debugging
- Provider no longer garbage collect atom values even when all useAtoms' are gone
- They will only be garbage collected by JS
- https://github.com/pmndrs/jotai/issues/84#issuecomment-703967151
> New impl dependents in state no gc

- .size-snapshot.json
- src/core/Provider.ts
- tests/error.test.tsx
This might be a bit controversial. 
Currently, we throw read errors in useAtom, but for write errors we throw them (or reject promises) in write function (more precisely SetAtom function).
This PR fixes some edge cases where it fails to return errors in a promise.
If a write function is async, we always return a promise, however, if a write function is sync, we may throw an error or return a promise which can contain an error. It's not very predictable for users.
Unless there's any better idea, it can't be helped much...
> fix: return write error in promise

- package.json
- rollup.config.js
- tsconfig.json
- yarn.lock
Only dev related changes. No need for a new version release.
> Update rollup plugins and fix their ordering #105

- .size-snapshot.json
- package.json
- src/core/Provider.ts
- tests/async.test.tsx
- tests/basic.test.tsx
- tests/error.test.tsx
- tests/setReactExperimental.ts
close #156 
The behavior introduced with use-context-selector v1.2 is confusing developers.
As it would only be required for experimental concurrent mode support,
this adds a detection and changes the behavior in legacy mode.
It revealed some bugs around pending state, and they are fixed.
> Detect react experimental and fix some bugs

- .size-snapshot.json
- src/utils/atomFamily.ts
close #155 
This adds a new functionality to atomFamily.
Typical use case would be to remove atoms if it's created a long time ago, and refresh them.
This use case is probably for experts. Naive shouldRemove can lead to infinite loop.
----
```js
const family = atomFamily(...)
family.setShouldRemove((createdAt, param) => createdAt + 60 * 1000 < Date.now())
```
> add shouldRemove in atomFamily

- .size-snapshot.json
- src/core/Provider.ts
- src/core/useAtom.ts
https://github.com/pmndrs/jotai/issues/159#issuecomment-720697657
It seems like some RN versions doesn't support Proxies.
https://github.com/pmndrs/jotai/issues/48#issuecomment-701025932
It's also reported before for IE11 compatibility.
This PR removes the usage of Proxies. It does reduce bundle size too.
@likern Would you please if this solves your use case? (Check codesandbox bot message how to install the bundle.)
> fix: avoid using proxy

- .size-snapshot.json
- docs/core.md
- src/core/Provider.ts
We have some discussions in discord, and found that this is missing.
The use cases of `initialValues` are:
- testing
- server side rendering
> feat: Provider initialValues prop

- docs/debugging.md
Add API and Usage documentation for the [`useAtomDevtools`](https://github.com/pmndrs/jotai/blob/master/src/devtools/useAtomDevtools.ts) hook to [`docs/debugging.md`](https://github.com/c0d3t3k/jotai/blob/devtools-docs/docs/debugging.md).
> Add Documentation for useAtomDevtools

- src/core/Provider.ts
- src/core/immutableMap.ts
closes #172 
@dai-shi Is this what you had in mind for this refactor?
Basically removes the need for the extra loop for the unique keys.
> refactor: implement mForEach

- .size-snapshot.json
- src/devtools/useAtomDevtools.ts
How about enabling devtools only in development mode? It would be a little bit better in production mode.
> chore: useAtomDevtools typing

- src/core/immutableMap.ts
- tests/immutableMap.test.ts
https://github.com/pmndrs/jotai/issues/184#issuecomment-725037679
Previously, the debug state is Map and not very easy to see in react devtools.
This fixes it by using objects.
> use object instead of map for debug state

- .size-snapshot.json
- src/utils/useSelector.ts
I noticed this while I was creating an example on codesandbox.
Would be nice if we can create a test to detect this. cc @Aslemammad
> fix(useSelector): do not call equalityFn before initialization

- package.json
- tests/async.test.tsx
- tests/basic.test.tsx
- yarn.lock
Close #208 
It's an edge case which had to dealt with upstream use-context-selector.
> fix: useEffect not called if another setState bails out

- .size-snapshot.json
- src/utils.ts
- src/utils/useResetAtom.ts
- tests/utils/useResetAtom.test.tsx
To continue the discussion in https://github.com/pmndrs/jotai/issues/217 I'm adding PR that will allow you to use `useResetAtom` in more cases.
* this exports `RESET` symbol, so bundle becomes slightly bigger
* add tests to cover:
* resetting read-write atom (but it does nothing special, I could have added `+1` or `* 2` to illustrate the point more)
* writing custom atom that could use `RESET` value just as a regular value or action (thus `atomWithReducer`, but I don't know if that's ok to create a test that tests both `atomWithReducer` and `useResetAtom`, in some sense this particular tests could be in either `useResetAtom.test.tsx` or `atomWithReducer.test.tsx`)
> export RESET symbol and add tests (#217)

- .size-snapshot.json
- src/utils.ts
- src/utils/atomWithReset.ts
- src/utils/useResetAtom.ts
* it wasn't possible before since RESET wasn't exported
* there's probably some good reason why we can put `RESET` symbol in its own file or in `useResetAtom`, but I don't know it
* this continues #221
> we can now split atomWithReset and useResetAtom

- docs/comparison.md
- docs/core.md
- docs/debugging.md
- docs/immer.md
- docs/nextjs.md
- docs/optics.md
- docs/persistence.md
- docs/showcase.md
- docs/utils.md
- package.json
- readme.md
* prettier is only running when files are committed, there probably more files that need to be formatted, I did `yarn prettier --write docs/*.md readme.md`
* it might be possible to set different code style for `md` files then for code. I tried for example with `semi: true` and `singleQuote: false`, but the amount of changes seemed about the same, as half of the code in docs is in one style and the other in other :)
> format md with prettier for more consistent code examples

- .size-snapshot.json
- src/core/atom.ts
- src/core/types.ts
- src/core/vanilla.ts
- src/optics/focusAtom.ts
As discussed in https://github.com/pmndrs/jotai/issues/238#issuecomment-745081350,
It was my bad in #233 to work around #235.
This PR reverts it to the previous version (of v0.11.3), still taking care of the issue discussed in #235 (and assuming #231 is a bug at least for now.)
> revert PrimitiveAtom type

- .size-snapshot.json
- src/core/Provider.ts
- src/core/vanilla.ts
close #243 
The current config for cjs build doesn't transpile `[...<iterator>]` well. There might be a way to change the babel config, but this PR just changes it in the code to `Array.from(<iterator>)` for now.
> fix: use array.from instead of spread operator for cjs

- package.json
- yarn.lock
Issue reported in https://github.com/dai-shi/use-context-selector/issues/35
This will allow preact users to use jotai with aliases:
```json
"alias": {
"react": "preact/compat",
"react-dom": "preact/compat",
"scheduler": false
}
```
> feat: preact support

- src/core/Provider.ts
- tests/provider.test.tsx
Currently `<Provider />` crashes as `InnerProvider` returns `undefined` when it has no children. React components may not return `undefined` so you get an error.
I know this is an edge case but imagine a component that conditionally renders something that uses `Provider`, like:
```tsx
return <Provider>{someCondition ? <ChildThatUsesJotai /> : undefined}</Provider>
```
I hit it in a unit test where I wanted to test jotai-based persistence of a component by unmounting the child (while keeping `Provider` alive) then remounting it and seeing if it retains the values.
Instead of the cast (which hides the bug), wrapping `children` in a Fragment makes sure this doesn't happen. The alternative would be to make it `children ?? null`, I don't have a strong opinion, I just picked one.
> Fix Provider crash when not having any children

- src/core/vanilla.ts
> Trying to read an atom value that is never used. This may not behave as expected. 
This warning message was something I wasn't sure how to deal with, when we read the atom value in `write` that is not initialized.
It turns out there is use case for this path.
So, it now does two things:
1. if the atom has the initial value, return it,
2. otherwise throw an error with a debug warning message.
> fix: proper/better warning message in write function

- package.json
- rollup.config.js
Looks like having cjs files and mjs files in the same directory is troublesome with webpack.
It's unfortunate, but put mjs files in `modules`.
Also drop iife.js assuming it's never used.
> fix: dist mjs files in modules

- .size-snapshot.json
- src/core/Bridge.ts
- src/core/Provider.ts
- src/core/contexts.ts
- src/core/useAtom.ts
- src/core/vanilla.ts
Having two contexts was somewhat for performance for the future.
But, if react supports use-context-selector natively in the future, we might not need this, furthermore, it doesn't improve performance as of now.
Having a single context simplifies code and possibly has room for improvements.
> chore: refactor with single context

- examples/mega-form/package.json
- examples/mega-form/yarn.lock
Since we now have `splitAtom` in mainline version of jotai, let's use that instead and not the CSB-build.
Not related to this PR:
Also, I tried upgrading to `^0.15.0` but it crashes (too many renders according to react). Is this something we should discover? Might be a bug from the provider-less mode.
> fix(examples): use officially released version of jotai for mega form

- src/core/Provider.ts
- src/core/contexts.ts
- src/core/vanilla.ts
follow-up #326
state is really atomic, but this allows an opt-in listener so that we can see all atoms from outside. (for debug purpose only)
> fix: provider debug state

- src/index.ts
- src/utils/useUpdateAtom.ts
- tests/utils/useUpdateAtom.test.tsx
This fixes `useUpdateAtom` for write without argument.
I'm not sure about the export of `SetAtom`, but I couldn't see any other way.
> Fix useUpdateAtom for write-only atoms

- src/utils/useResetAtom.ts
This refactors `useResetAtom` with almost identical implementation as `useUpdateAtom` - This saves an atom creation.
As commented, `_update` stays for compatibility changes, but I propose removing it before v1.
> Refactor useResetAtom with secret internals

- .size-snapshot.json
- src/immer/withImmer.ts
- src/optics/focusAtom.ts
- src/utils/selectAtom.ts
- src/utils/splitAtom.ts
- src/utils/weakCache.ts
- tests/immer/withImmer.test.tsx
- tests/optics/focus-lens.test.tsx
- tests/optics/focus-prism.test.tsx
- tests/optics/focus-traversal.test.tsx
- tests/utils/selectAtom.test.tsx
- tests/utils/splitAtom.test.tsx
While discussing with @Thisen, I noticed that we can create useMemo alternative for derived atoms. @merisbahti said he wanted to use `splitAtom` in render without useMemo. So, here it is.
(I hope I didn't miss something fundamental...
> feat: weak cache to avoid infinite loop without useMemo

- src/core/atom.ts
- src/core/types.ts
We can avoid a little bit of repetition by declaring Read and Write types.
> [Types] Add Read & Write types, reduce duplicate type declaration

- .size-snapshot.json
- src/core/useMutableSource.ts
- tests/optimization.test.tsx
This PR fixes #355. Actually, when we call the write function on an atom, it will change it correctly. Still, as we use uMS emulation, for now, it causes an unexpected extra re-render for some atoms that hold the previous value, and they don't change, but uMS cause a re-render for that.
> Refactor uMS to avoid extra re-renders

- src/utils/waitForAll.ts
- tests/utils/waitForAll.test.tsx
https://github.com/pmndrs/jotai/pull/358#discussion_r602177739
Sorry, my suggestion back then was wrong. We are **catching** promises, so we should **throw** what we caught. This is correct.
> fix: waitForAll with throw

- src/query/atomWithQuery.ts
This takes the same `equalityFn` signature from `selectAtom` and adds it to the `atomWithQuery` helper. I have found this very helpful in my apps to help control rerenders while the query revalidates. Currently, if the query is set to refetch on an interval, when it sets the data atom again it will cause any component that uses the data to rerender even if nothing in the data has changed.
Happy to explore other options, but this works for me currently.
> feat: add equality fn to atomWithQuery

- src/core/atom.ts
- src/core/types.ts
- src/immer/atomWithImmer.ts
- src/utils/atomWithReducer.ts
- src/utils/atomWithReset.ts
Avoids having `never` on function return type.
> fix: atom creator types

- src/utils/useAtomCallback.ts
- tests/utils/useAtomCallback.test.tsx
fix https://github.com/pmndrs/jotai/issues/398
It's a hack. I'm not exactly sure why the original overloads didn't work — that part TS (probably something to do with covariance/contravariance rules) is still something I haven't explored much.
This fix works, but it has bad UX. Could be improved by inlining the error type (right now the intellisense doesn't display the error message).
And of course, someone with more TS knowledge can probably make the overloads work properly. Feel free to close.
> fix types for 3-arg useAtomCallback

- docs/api/redux.md
- package.json
- src/redux.ts
- src/redux/atomWithStore.ts
- tests/redux/atomWithStore.test.tsx
- yarn.lock
If jotai/zustand #419 is a thing, why not `jotai/redux` ?
But then my question comes again. what should be in and out.
There could be a real use case though. Applying jotai gracefully to existing redux apps.
> feat: jotai/redux

- src/core/atom.ts
- src/core/types.ts
- src/immer/atomWithImmer.ts
- src/optics/focusAtom.ts
- src/redux/atomWithStore.ts
- src/utils/atomWithReducer.ts
- src/utils/atomWithReset.ts
- src/valtio/atomWithProxy.ts
- src/zustand/atomWithStore.ts
- tests/async.test.tsx
https://github.com/pmndrs/jotai/discussions/433#discussioncomment-631065
> v0.16.1 introduces `NonFunction` which seems proper in types, but not good in DX. We'd like to improve it.
Here it is.
> fix: improve types without NonFunction in atom()

- src/core/Provider.ts
- src/core/contexts.ts
- src/core/vanilla.ts
- src/devtools/useAtomsSnapshot.ts
This PR splits the store for production and development mode.
This brings us back to a single context, without breaking changes.
> Devtools: Atoms in store in dev mode

- src/core/vanilla.ts
Now with #431, it is a valid use case. So the warning is false negatives.
> chore: remove warning for deleting atom with read promise

- src/query/atomWithQuery.ts
- tests/query/atomWithQuery.test.tsx
While working on #463, I got a better idea around `initAtom`. This is to follow the pattern.
> chore(feat/query): refactor atomWithQuery

- src/query/atomWithQuery.ts
The destroy function loses the observer, So we save the observer and bind it later.
> fix(atomWithQuery): Error: Uncaught [TypeError: Cannot set property 'listeners' of undefined]

- tests/onmount.test.tsx
- tests/utils/splitAtom.test.tsx
It's more or less a hack. I don't know the root cause.
Also, fixes to prefer getByTestId to findByTestId, which should be good.
> chore: fix warnings in tests

- src/core/vanilla.ts
- src/devtools/useAtomsSnapshot.ts
- src/devtools/useGotoAtomsSnapshot.ts
- tests/onmount.test.tsx
- tests/utils/splitAtom.test.tsx
We use the following keywords and avoid `XXX` which is ambiguous.
```ts
// FIXME this means, it's working but should be improved
// TODO this means, it's not implemented and should be done
// HACK this means, it's not very nice but it can't be helped
// NOTE this means, it's something that should be understood
```
> chore: avoid using XXX in code comments

- .size-snapshot.json
- src/core/vanilla.ts
ref: https://github.com/pmndrs/jotai/issues/231#issuecomment-851075102
I just found it was possible to set values to an atom that has `read` function.
This is not a supported pattern, and should be error to avoid misusing.
> fix: throw error for prohibited write operations

- src/core/atom.ts
- src/core/contexts.ts
- src/core/useAtom.ts
- src/core/vanilla.ts
- tests/error.test.tsx
The API is confusing especially in TypeScript and the implementation is too tricky.
We remain error handling as `TODO`.
> feat: drop returning promise by writeAtom/setAtom

- src/core/vanilla.ts
because it may not work as expected without dependencies. we would revisit this as we collect more use cases.
> chore: warn initial value for derived atom

- .size-snapshot.json
- src/query/atomWithQuery.ts
- tests/query/atomWithQuery.test.tsx
I found `useQuery` in react-query uses `fetchOptimistic` for suspense.
This is undocumented, but it should solve some potential issues in atomWithQuery.
(Previously, there's a risk of memory leak. I'm so glad to get rid of stateAtom which uses mutable state.)
> chore(jotai/query): refactor atomWithQuery

- src/core/Provider.ts
While starting to test our state, I noticed a warning from jest/hooks-testing-library about needing to wrap a function in Provider with `act`. This is the change @dai-shi recommended and I've tested it locally.
> fix: disable useDebugState in test env

- src/query/atomWithQuery.ts
- src/query/queryClientAtom.ts
With #516, setting initialValue in Provider for derived atoms is not recommended.
This PR provides a primitive atom for queryClient. This allows to set the atom in useEffect too.
> fix(query): queryClientAtom for initialValues

- tests/utils/splitAtom.test.tsx
expect console.warn to be called.
> chore(utils): splitAtom test

- .size-snapshot.json
- src/xstate/atomWithMachine.ts
During recent conversation in #289,
I noticed there's potentially a case we want to construct `options` from atoms.
So, this supports `getOptions`.
> fix(xstate): support getOptions

- src/core/contexts.ts
- tests/devtools/useAtomsSnapshot.test.tsx
> fix(snapshot): Add initialValues to debugstore init

- .size-snapshot.json
- src/query.ts
- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
- tests/query/atomWithInfiniteQuery.test.tsx
This takes the same atomWithQuery code but updates it to use the InfiniteQueryObserver, I've found that it works really well! [These lines](https://github.com/pmndrs/jotai/pull/571/files#diff-eba32cd62a32f599ef9f077a5ee759390743d66de02c76e91c36fbf0dde65bdaR137-R153) are the biggest change away from the `atomWithQuery` implementation.
**[Click here for a codesandbox](https://codesandbox.io/s/react-typescript-forked-2bfki?file=/src/App.tsx)**
example atom:
```ts
const someAtom = atomWithInfiniteQuery<{ count: string }, null>(get => {
return {
queryKey: 'someInfiniteQuery',
queryFn: context => {
const { pageParam } = context;
return { count: pageParam || '0' };
},
getNextPageParam: (lastPage, allPages) => {
const { count } = lastPage;
return (parseInt(count) + 1).toString();
}, …
```
> feat: add atomWithInfiniteQuery

- .size-snapshot.json
- src/query/atomWithQuery.ts
This takes the pattern of using the `observer` from the `atomWithInfiniteQuery` implementation to refetch vs the queryClient method that was used previously. Suspense behavior has not been impacted.
> fix(query): use observer for refetch

- .size-snapshot.json
- src/utils/selectAtom.ts
- src/utils/splitAtom.ts
This is basically some refactor, as the original version I created had an issue with multiple provider scenario.
Basically, we shouldn't use/depend on any variable outside atoms.
`refAtom` is kind of a hack, but I don't know if there's a better way now.
> fix(utils): refactor to avoid variable outside atom

- .size-snapshot.json
- src/query/atomWithInfiniteQuery.ts
So this was a strange bug that I came upon. It would happen where I had an `atomWithInfiniteQuery` already loaded, and then navigated to a page that had that same query. It seems there is some [default cancellation behavior](https://github.com/tannerlinsley/react-query/blob/16b7d290c70639b627d9ada32951d211eac3adc3/src/core/infiniteQueryBehavior.ts#L118) in the way infiniteQueries work in react query.
I think this solution makes sense, and it fixes my bug (without this, the application breaks).
> fix(query): gracefully handle CancelledError

- package.json
We had some discussions in https://github.com/pmndrs/valtio/pull/169.
Like valtio, jotai uses lots of module states.
So, this change suffers from dual package hazard.
However, we feel the benefit is bigger because cjs build is built for traditional browsers and esm build is always recommended if possible.
Would anyone please try this, and if it works fine? (You can install the codesandbox build with npm/yarn.)
> fix: package.json exports to have import

- .size-snapshot.json
- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
- tests/query/atomWithQuery.test.tsx
While doing some more testing, I noticed that on mount a query would automatically refetch even though I had provided `initialData` to it. I could not stop this behavior -- based off of reading https://react-query.tanstack.com/guides/initial-query-data#_top, it is the case that initialData will be treated as fresh until the staleTime has been met, or based on other user options passed (meaning a fetch should not happen until it become stale, and there have been some refetch options passed)
Because we were automatically running the fetchOptimistic method regardless of if initialData was passed, we were causing an unneeded fetch to happen. React query will pick up and take over and do all the fetching if needed when there is initialData. We are already subscribing on mount, so there is no …
> fix(query): subscribe instead of fetch if initialData

- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
This is basically a commit reverting #386.
https://github.com/pmndrs/jotai/pull/589#discussion_r668949661 shows an alternative method, so I think this is not necessary.
> breaking(query): remove optional equalityFn from atomWith(Infinite)Query

- src/query.ts
- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
- src/query/queryClientAtom.ts
- src/redux/atomWithStore.ts
- src/urql/atomWithMutation.ts
- src/urql/atomWithQuery.ts
- src/urql/atomWithSubscription.ts
- src/urql/clientAtom.ts
- src/utils/atomWithDefault.ts
- src/utils/atomWithStorage.ts
- src/utils/selectAtom.ts
- src/utils/splitAtom.ts
- src/valtio/atomWithProxy.ts
- src/xstate/atomWithMachine.ts
- src/zustand/atomWithStore.ts
An internal discussion with @aulneau revealed that many of utils/integrations don't support atom scope properly, especially when we create internal atoms in a function.
This PR addresses the issue. Note this affects only the case using `scope`, which is mainly for library usage.
> fix: support atom scope outside core

- .size-snapshot.json
- package.json
- src/rxjs/atomWithObservable.ts
**This is a draft / WIP.**
Ref: #234
This converts `jotai/rxjs` over to a generic `atomWithObservable` that potentially supports all `Observable` libraries that adhere to the [Observable proposal.](https://github.com/tc39/proposal-observable)
To replace `first` the initial subscription unsubscribes at the earliest possible time, which takes synchronous (non-deferred) results into account. The `resultAtom.onMount` function will also now reuse the subscription if possible and otherwise start a new subscription, to match the previous implementation closely in its double-subscription behaviour.
> feat(rxjs): Convert atomWithObservable to Observable spec

- .size-snapshot.json
- package.json
- src/rxjs.ts
- src/utils.ts
- src/utils/atomWithObservable.ts
- tests/utils/atomWithObservable.test.tsx
Thanks to #593, atomWithObservable doesn't depend on rxjs, so moving to utils. Modified a bit to fit with coding styles.
> breaking(rxjs): move atomWithObservable in utils

- src/utils/atomWithObservable.ts
There was a tiny mistake in types. (Should we add expectType in tests?)
> fix: atomWithObservable type

- examples/hacker_news/src/App.tsx
- examples/todos/src/App.tsx
- examples/todos_with_atomFamily/src/App.tsx
- tests/items.test.tsx
- tests/query/atomWithQuery.test.tsx
- tests/urql/atomWithQuery.test.tsx
- tests/utils/atomFamily.test.tsx
- tests/utils/waitForAll.test.tsx
Response to the call for this [issue](https://github.com/pmndrs/jotai/issues/26#issuecomment-691588119)
> The utility hooks can get big. I need someone to volunteer to help it, especially for documentation & examples.
> fix(examples, tests): use `useUpdateAtom` and write-only atoms to avoid re-render

- package.json
- src/valtio/atomWithProxy.ts
- tests/valtio/atomWithProxy.test.tsx
- yarn.lock
This is a test for the fix of the infinite loop bug (https://github.com/pmndrs/jotai/issues/624) that happens when working with promises and atomWithProxy.
> test(valtio): infinite loop bug

- tests/urql/atomWithQuery.test.tsx
- tests/urql/atomWithSubscription.test.tsx
Introduce passing tests for the use case of switching clients for both subscriptions and queries. The tests are passing and are meant for better coverage of this as it is a rather widespread use-case (authentication involves switching clients) that we don't want breaking.
**This PR is a partial of https://github.com/pmndrs/jotai/pull/635 (in case 635 needs further discussion). Only merge it if 635 will become delayed. If 635 is OK, merge that instead**
> test(urql): add tests for client switching

- src/utils/weakCache.ts
- tests/utils/waitForAll.test.tsx
> fix(weakCache): Replace recursion with while loop to avoid too much recursion

- .size-snapshot.json
- src/core/Provider.ts
- src/core/contexts.ts
- src/core/useAtom.ts
- src/core/useMutableSource.ts
- src/devtools/useAtomsSnapshot.ts
This is to follow https://github.com/pmndrs/valtio/pull/208 (we use the same code.)
@Thisen once suggested to have precise typing in useMutableSource.ts. This covers it.
> refactor(core): useMutableSource emulation without symbol and any

- .size-snapshot.json
- src/core/Provider.ts
- src/core/contexts.ts
- src/devtools/useAtomsSnapshot.ts
- src/devtools/useGotoAtomsSnapshot.ts
- src/utils.ts
- src/utils/useHydrateAtoms.ts
- tests/utils/useHydrateAtoms.test.tsx
Adds a new hook, that can hydrate an atom with a initial value.
Primary use case is SSR/Next.js, but it's not bound to anything.
Please supply your use cases, so we can experiment/test this hook properly.
> Feature: useHydrateAtoms

- src/core/Provider.ts
- src/core/contexts.ts
- src/core/useAtom.ts
- src/devtools/useAtomsSnapshot.ts
- src/devtools/useGotoAtomsSnapshot.ts
- src/index.ts
- src/utils/useHydrateAtoms.ts
- src/utils/useResetAtom.ts
- src/utils/useUpdateAtom.ts
This is just a refactoring to rename `Store` to `ScopeContainer` and so on.
> refactor: rename store to scope container

- .size-snapshot.json
- src/devtools/useAtomsSnapshot.ts
> Fix(useAtomsSnapshot): Only use values in snapshots

- .size-snapshot.json
- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
- tests/query/atomWithQuery.test.tsx
While experimenting with some of the new features in react query, specifically the [`persistQueryClient`](https://react-query.tanstack.com/plugins/persistQueryClient) stuff, I found a bug where if a query has been hydrated via methods exported by react-query (for SSR, or for this new persistence feature), our atom would not handle it correctly.
This fixes that by checking to see if there is data for the queryKey, if there is, treat it the same as if `initialData` was passed.
> fix(query): improve initial data method

- .size-snapshot.json
- src/core/store.ts
@Sawtaytoes pointed out that the code is duplicated. Good eyes.
This is a small refactor to reduce bundle size and maybe code readability.
> refactor(core): remove duplicated code

- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
- src/query/types.ts
- tests/query/atomWithInfiniteQuery.test.tsx
- tests/query/atomWithQuery.test.tsx
This adds the `enabled` functionality described here -> https://react-query.tanstack.com/guides/disabling-queries#_top
When the user passes any value for `enabled`, the data value becomes potentially undefined. I've added two tests, one for disabled at start, and one for toggling enabled functionality.
@dai-shi lmk what you think of this implementation, and if it's good I'll do it to the infinity query atom too!
> feat(query): enabled functionality

- .size-snapshot.json
- package.json
- src/query/atomWithInfiniteQuery.ts
- tests/query/atomWithInfiniteQuery.test.tsx
- yarn.lock
This enables support of the new feature where you can refetch a given page for an infinite query, see https://github.com/tannerlinsley/react-query/pull/2557
> feat(query): infinite query page refresh

- .size-snapshot.json
- src/core/store.ts
- src/query/atomWithQuery.ts
- tests/query/atomWithQuery.test.tsx
#689 changed `writeAtom` to return a promise. This is a follow-up PR to cover some edge cases.
- remove extra code in code that is basically unnecessary in jotai core
- make atomWithQuery write function to return a promise with fixing tests in jotai/query
> fix(core,query): handle edge cases with writeAtom returning a promise

- src/core/store.ts
- tests/error.test.tsx
- tests/utils/atomWithObservable.test.tsx
When changing a dependency for an atom in an error state, the derived atom's read function is re-run.
We'd expect that if that re-run is successful, `useAtom` will return the new value.
This is currently the case with sync atoms, but not async atoms. This PR fixes that, and adds tests (the async variant was failing, but the sync one wasn't).
Fixes #601
> fix(core): Allow retries for errored async reads

- src/utils.ts
- src/utils/loadable.ts
- tests/utils/loadable.test.tsx
Fixes: https://github.com/pmndrs/jotai/issues/672 (or at least tries to)
This implements loadable as discussed in the mentioned issue.
I can't get all edge-cases to work. In particular, recovering from error, when an atom goes through these states:
`suspense -> error -> suspense -> resolved`
Going from `error -> suspense` does not trigger a re-render.
I think this might need some changes to core, as I suspect by catching the error/promise, we are preventing some state-keeping logic from happening.
@dai-shi could you have a look? It's the last test in `loadable.test.tsx` that's failing.
> feat(utils): Add loadable

- .codesandbox/ci.json
- package.json
Since Vercel is default on Node 12, lets use that for now to avoid errors on default deployments.
> Switch back to Node 12

- src/core/Provider.ts
- src/core/contexts.ts
- src/core/store.ts
- src/core/useAtom.ts
- src/devtools/useAtomsSnapshot.ts
- src/devtools/useGotoAtomsSnapshot.ts
- src/utils/useHydrateAtoms.ts
- src/utils/useResetAtom.ts
- src/utils/useUpdateAtom.ts
This simplifies scope container a lot. Also, this fixes memory leak issue in DEV.
> refactor(core,utils,devtools): add dev methods in store

- src/core/store.ts
- src/core/useAtom.ts
- src/utils/loadable.ts
- tests/utils/loadable.test.tsx
I think the library shouldn't modify thrown errors.
Unfortunately, the implementation of `loadable` gets hacky, but it passes the test (it's refactored, but specs are not changed. cc @Pinpickle )
> fix(core,utils): support unknown error type

- src/core/store.ts
- src/core/useAtom.ts
This is simple refactoring to hide `flushPending` in store, and expose `commitAtom` instead. There are some other trivial things like renaming, moving code.
> refactor(core): commitAtom in store

- tests/dependency.test.tsx
- tests/error.test.tsx
- tests/scope.test.tsx
to avoid testing with other console error messages. there can be room for improvement.
> refactor(tests): checking console error messages

- src/core/store.ts
- tests/async.test.tsx
fix #742.
This is actually something I wasn't very confident with in the logic. Happy to have a fix 🎉 .
> fix(core): resume from suspense on derived atom with async atom dependency

- src/devtools/useAtomDevtools.ts
Previously, `useAtomDevtools` only accepts primitive atoms (more precisely `WritableAtom<Value, Value>` type). Now, with this PR, it supports read-only atoms (`Atom<Value>` type).
close #808
> feat(devtools): read-only atom support in useAtomDevtools

- src/core/store.ts
we should clear obsoleted invalidated revision, so that we can skip checking.
there would be room for improvement in AtomState types. will revisit it in the future.
> refactor(core): improve invalidated revision

- readme.md
This updates the readme with a link to Daishi's [egghead course on Jotai](https://egghead.io/courses/manage-application-state-with-jotai-atoms-2c3a29f0) with a nice banner.
> Update readme with a CTA for jotai egghead course

- .gitignore
The new directives are for files generated by [GitHub Codespaces](https://github.com/features/codespaces). 😀
> chore: extend gitignore directives

- docs/guides/nextjs.mdx
Adds documentation for syncing Jotai to the Next.js router
> Docs: Sync with Next.js router

- package.json
- patches/xstate+4.26.0.patch
- src/core/store.ts
- src/urql/atomWithQuery.ts
- src/utils/atomWithStorage.ts
- src/xstate/atomWithMachine.ts
- tsconfig.json
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#exact-optional-property-types
> refactor(types): enable exactOptionalPropertyTypes

- src/utils/loadable.ts
- src/utils/selectAtom.ts
- tests/utils/loadable.test.tsx
- tests/utils/selectAtom.test.tsx
#713 changed the type signature for atoms. The `data` field for a loadable ended up incorrectly typed with a promise, when it should be unwrapped.
A similar issue occurred with `selectAtom`
This adds a `ResolveType` (used in other files) to fix it.
> fix(utils): Unwrap loadable/selectAtom promise types

- src/core/store.ts
It's prohibited to write a read-only atom. The error message wasn't meaningful. Let's fix it.
> fix(core): improve read-only atom error message

- src/core/atom.ts
- src/core/useAtom.ts
Just for a little more consistency. (In the future, we would be refactoring all async typing with `Awaited`.)
> fix(type): improve core typing

- src/core/atom.ts
- src/core/store.ts
This experimental feature is first introduced in #539.
We don't get much feedback, and it's still experimental.
But, we hope to make it stable in the future. For now, this makes it an option object and no longer warns.
> fix(core): unstable_promise option in write getter

- src/utils/loadable.ts
- tests/utils/loadable.test.tsx
This is full refactor of the loadable util, introduced in #734. The previous implementation doesn't work with #854.
> fix(utils): refactor loadable

- src/urql/atomWithQuery.ts
- tests/urql/atomWithQuery.test.tsx
This is a minor fix to avoid duplicated listener invocations.
Tests are passing, but I might be misunderstanding the expected behavior.
We would like to revisit it in the future. Contributor wanted.
> fix(urql): atomWithQuery for edge cases

- src/utils/waitForAll.ts
TypeScript v4.5 handles function overload correctly (strictly). We didn't even need the overload. Thanks to someone who gave a right direction.
> fix(utils): fix waitForAll types

- src/core/store.ts
- tests/dependency.test.tsx
> fix(core): Bail out of atom.write when atom update and current value are equal

- docs/api/utils.mdx
Hi, while researching atomWithHash, I found the PR that added options (#758) but they were not documented on the site. I’ve added documentation for options.
> docs(website): add documentation for atomWithHash options

- src/core/Provider.ts
- src/core/store.ts
- src/core/useAtom.ts
- src/devtools/useAtomsSnapshot.ts
Thanks to @Thisen 's work in #878, it reveals my misconception. It's almost from the beginning and I thought it covered the #877 case, which was wrong. Based on the new tests, this PR fixes my mistake and it works with stricter types.
> fix(core): refactor atomState in store

- docs/api/utils.mdx
Adding a table of content to the Utils doc page. Added a one line description of each utility to make it easier to find the one someone is looking for.
As discussed [here on Twitter](https://twitter.com/dai_shi/status/1468926381195415555?s=20)
> doc: Added TOC to Utils page

- tests/async.test.tsx
- tests/query/atomWithQuery.test.tsx
Unfortunately, the timeout tuning in #850 seems to cause CI failure several times. This is to address it, hopefully.
Note that I'm not happy with this. If anyone has an idea to make it work with fake timers stably, it's much appreciated.
> chore(tests): tweak timeouts

- src/utils/waitForAll.ts
- tests/types.test.tsx
- tests/utils/waitForAll.test.tsx
- tests/utils/waitForAll.types.test.tsx
Example:
```typescript
const numberAtom = atom(0)
const stringAtom = atom('')
const [num, str] = useAtomValue(waitForAll([numberAtom, stringAtom]))
```
Previously, in the code above, both `num` and `str` would have the type `number | string | undefined`. With this fix, `num` has the type `number` and `str` has the type `string`.
> fix(type): Fix types on waitForAll to work with destructuring

- src/core/store.ts
- tests/basic.test.tsx
> fix(core): resolve infinite loop with derived atoms with onMount

- docs/api/utils.mdx
I think these got broken during one of the recent doc improvements, this should get it working again
> docs: Fix broken util links

- src/core/store.ts
- src/devtools/useAtomsSnapshot.ts
- tests/basic.test.tsx
This is just a refactor of an internal DEV-only function. When we refactored with `DEV_GET_MOUNTED_ATOMS`, we no longer need to notify each updating state, and it's cleaner and should behave better.
> fix(core): refactor internal state listener

- src/core/Provider.ts
- src/core/store.ts
- Refactor code for a little more readability
- createReadDependencies not to return a new reference if the content is the same
- handle edge cases in versioned write for #837 (very hacky for now)
> fix(core): refactor with createReadDependencies

- tests/utils/selectAtom.test.tsx
https://github.com/pmndrs/jotai/pull/936#issuecomment-1008447836
tbh, I hoped we didn't need to support this usage. but, as `selectAtom` is a kind of an escape hatch anyway, it makes sense to make it conservative.
> fix(tests): add a test for selectAtom with async and equality fn usage

- src/babel/plugin-react-refresh.ts
- tests/babel/plugin-react-refresh.test.ts
Fixes #891.
For simplicity, we require that the atom is in module scope for the cache to work. If we wanted to support the case in #891, we need need to depend on the call order (like hooks), but I think that's too complex for current use cases. If it gets requested, we can investigate what we can do.
> fix(babel): Require that atom is in module scope for react refresh

- src/core/store.ts
- tests/async.test.tsx
- tests/basic.test.tsx
fix #947 
(edit by @dai-shi) this is done by a hacky way. wish to have a nicer way.
> fix(core): handle an edge case of changing dependencies without changing atom value

- src/core/store.ts
- tests/basic.test.tsx
fix #942.
(edit by @dai-shi) the solution seems a little bit hacky and may break other use cases. we look for more cases and tests.
> fix(core): handle edge cases, not to mount dependency atoms if the atom is not mounted

- tests/async.test.tsx
- tests/query/atomWithInfiniteQuery.test.tsx
- tests/urql/atomWithQuery.test.tsx
Not pretty sure how this actually helps or not, but not harmful.
We need to find a way to make CI tests stable. Fake timers might do, but I kind of gave up once. Any volunteers?
> chore(tests): tweak some tests for CI

- docs/guides/atoms-in-atom.mdx
- docs/guides/no-suspense.mdx
- docs/guides/react-native.mdx
- docs/guides/resettable.mdx
- readme.md
Based on recent conversation I've written out documentation on the functions I used to get AtomWithStorage working effectively on React Native.
> Add documentation for react-native

- src/core/store.ts
- src/utils/atomWithStorage.ts
- breaking(core): remove deprecation warning of an old unstable feature (which has never been a public api) e4921e5365165b5837435182a3b4d5d4967e9064
- breaking(utils): make atomWithStorage storage.removeItem necessary d54f7606e88f06cbb5871e4cbfa735755764b0f2
Both are warned as deprecated in the previous versions.
> breaking(core,utils): remove some deprecated features

- docs/utils/atom-with-storage.mdx
- src/utils/atomWithStorage.ts
Adds `subscribe` to `defaultStorage` for `atomWithStorage`.
The `subscribe` listens to `storage` events.
Closes #882.
> feat(utils/atomWithStorage): Add subscribe to storage events in defaultStorage

- src/utils/atomWithObservable.ts
- tests/utils/atomWithObservable.test.tsx
`atomWithObservable` seems to be not resubscribing to observable when a component is being hidden and then shown again. 
There is a test reproducing it and also a [codesandbox](https://codesandbox.io/s/wizardly-resonance-28rvue?file=/src/App.js): atom value updates when clicking on a document, but if you hide/show component, it doesn't update anymore.
> Fix `atomWithObservable` is not resubscribed after remount

- src/core/atom.ts
- src/core/suspensePromise.ts
- src/core/useSetAtom.ts
- src/utils/weakCache.ts
Just minor refactoring.
I noticed some of types are exported but not considered as public api, so commented. (inspired by #1012)
> chore(types): refactor imports and add comments

- docs/guides/debugging.mdx
hyper links in [Frozen Atom](https://jotai.org/docs/guides/debugging#frozen-atoms) is too old, needs some update.
> [docs] Update debugging link

- package.json
- src/devtools/types.ts
- src/devtools/useAtomDevtools.ts
- src/devtools/useAtomsDevtools.ts
- yarn.lock
This PR tries to bring the native `window.__REDUX_DEVTOOLS_EXTENSION__` types from redux devtools and then avoids some custom types which may be incorrect in some cases!
> fix(devtools): better types with official devtools extension types

- src/babel/plugin-debug-label.ts
- src/babel/utils.ts
- tests/babel/plugin-debug-label.test.ts
This PR adds support for the babel plugin to add `debugLabel` for our atom utils.
Closes #1038.
> Add support for debugLabels for atom utils

- website/src/components/search-modal.js
@sandren 
To maintain the website functionality, I fix this first. Thanks!
As picture, currently the title of search result is invisible.
> [website] fix website searchbar title visibility

- docs/advanced-recipes/atom-creators.mdx
- docs/advanced-recipes/large-objects.mdx
- docs/api/babel.mdx
- docs/api/core.mdx
- docs/api/utils.mdx
- docs/basics/async.mdx
- docs/basics/comparison.mdx
- docs/basics/concepts.mdx
- docs/basics/primitives.mdx
- docs/basics/showcase.mdx
- docs/introduction.mdx
I just made a few small changes to the docs, to simplify some of the language and clean it up a little bit.
> fix: some language changes and minor typo fixes

- docs/basics/comparison.mdx
> docs: fix typo in `comparison.mdx`

- src/core/Provider.ts
- src/core/useDebugState.ts
- src/core/useSetAtom.ts
- src/urql/clientAtom.ts
- tests/async.test.tsx
- tests/basic.test.tsx
- tests/dependency.test.tsx
- tests/utils/atomFamily.test.tsx
- tests/utils/waitForAll.test.tsx
Looks like I overlooked some changes in #968 (and a slight one in #989).
This separates `useDebugState.ts` and fixes `__DEV__` usage. Our source code shouldn't depend on `process.env`.
For `jotai/urql`, the fix might not be ideal, but at least it avoids errors. Hope to find a better solution in the future.
> fix(core,urql): useDebugState and some envvar handling

- docs/utils/atom-with-observable.mdx
- src/utils/atomWithObservable.ts
- tests/utils/atomWithObservable.test.tsx
Reimplementation of initial data option for `atomWIthObservable` inspired by #875 + some refactoring and simplification of `atomWithObservable` code
> fix(utils): Initial data for atomWithObservable 

- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
close #1086 
This was a silly mistake, but can't be noticed without a test.
> fix(utils): undefined bug with no entry in storage

- src/core/store.ts
- tests/async.test.tsx
> fix(core): handle returning infinite promise in derived atoms

- src/devtools/useAtomDevtools.ts
- tests/devtools/useAtomDevtools.test.tsx
This PR tries to achieve what we achieved in https://github.com/pmndrs/zustand/pull/880 and #1076  so we can add an option called `enabled` for better testing/dev env friendly errors/warnings!
This PR is for useAtomDevtools.
> feat(devtools): enabled option in useAtomDevtools

- src/core/store.ts
- tests/async.test.tsx
- tests/utils/loadable.test.tsx
fix https://github.com/pmndrs/jotai/issues/1114
> fix(utils): resolve infinite loop with loadable of derived async atom in some cases

- docs/basics/async.mdx
As discussed in #1112, I've made the warning about using a `Provider` inside a `Suspense` a bit more noticeable.
Initially, I wanted to create a section with a heading and the paragraph, but I think the yellow box (blockquote) inside the "Suspense" paragraph makes more sense.
Do you think this is okay? For example, should I write what could happen if the `Provider` contains no `Suspense`?
> docs: warn about usage of `Provider` inside `Suspense`

- src/core/store.ts
- tests/transition.test.tsx
> fix(core): improve re-render behavior with useTransition

- src/urql/atomWithQuery.ts
Despite the runtime check (`isOperationResultWithData`), there is a key `data` in the result, but the value is `undefined` in case of error. Let's retain optional `data` definition from `urql` `OperationResult`
> fix(urql): atomWithQuery: improve isOperationResultWithData to avoid `undefined` in case of error

- docs/basics/primitives.mdx
- docs/utils/select-atom.mdx
@dai-shi I know you wanted to talk about `selectAtom` at this point, but I'm not sure why it's related, as it will still cause an infinite loop if used directly in the `useAtom`
I tested this:
```typescript
const [value] = useAtom(selectAtom(atom(0), (val) => val))
```
On the first render it does okay, but as soon as there is another render triggered by something else, this will cause an infinite loop.
I may be missing something about this selectAtom, for me it was just a fancy tool for redux lovers :p
> fix(docs): added info about infinite loop on useAtom

- tests/basic.test.tsx
- tests/utils/atomFamily.test.tsx
I can't completely remove `IS_REACT18`, unfortunately. Hope to improve it in the future.
> refactor(tests): better handling with React 18 behavioral difference

- docs/utils/atom-with-observable.mdx
- src/utils/atomWithObservable.ts
- tests/utils/atomWithObservable.test.tsx
@dai-shi As discussed this PR builds on https://github.com/pmndrs/jotai/pull/1157
- I added more tests for some of the edge cases
- I fixed some known and unknown issues that are covered by the new tests
This is the test result with the __current__ implementation:
This is the test result __new__ implementation:
Fixed issues:
- Emitted values between the initialValue and onMount are no longer ignored
- Falsy initial values are no longer ignored (`0`, `false`, `''`, etc.)
- If the observable is an `BehaviourSubject` or already has a value, `Suspense` is no longer required.
- If the observable never emits and no initial value is provided, the subscription is cancelled after 10 seconds.  This value can be configured with the `timeout` option
- I implemented this solution, based on your …
> fix(utils): fix memory leaks and other issues in atomWithObservable

- docs/api/devtools.mdx
- docs/basics/primitives.mdx
- docs/guides/debugging.mdx
- src/core/Provider.ts
- src/devtools.ts
- src/devtools/useAtomsDebugValue.ts
- src/devtools/useDebugState.ts
- tests/async.test.tsx
- tests/basic.test.tsx
- tests/dependency.test.tsx
- tests/transition.test.tsx
- tests/utils/atomFamily.test.tsx
- tests/utils/waitForAll.test.tsx
close #1180 
We plan to release this in a minor version update, even though this is technically breaking change in Provider's behavior in DEV-only environments.
---
Previously, if you use `<Provider>`, `useDebugValue` is automatically used in the dev mode and you can never disable it.
```jsx
import { Provider } from 'jotai'
const Root = () => (
<Provider>
<App />
</Provider>
}
```
Now, to get the same behavior, you need to use the `useAtomsDebugValue` explicitly.
```jsx
import { Provider } from 'jotai'
import { useAtomsDebugValue } from 'jotai/devtools'
const DebugAtoms = () => {
useAtomsDebugValue()
return null
}
const Root = () => (
<Provider>
<DebugAtoms />
<App />
</Provider>
}
```
> feat(devtools): expose useAtomsDebugValue from jotai/devtools

- docs/basics/primitives.mdx
Following-up [this issue](https://github.com/pmndrs/jotai/issues/1175) to clarify in the docs that extra-rerenders even if atoms value didn't change is an expected behaviour
> docs(primitives): Educate idempotent components

- docs/guides/nextjs.mdx
Follow-up of [this issue](https://github.com/pmndrs/jotai/issues/1190), where it was unclear that NextJS should use `Provider` while we see no use-case without it.
@dai-shi Please review carefully, I'm not sure what I'm talking about too well
> docs(nextjs): educate provider

- .eslintrc.json
- src/core/atom.ts
- src/core/contexts.ts
- src/core/store.ts
- src/devtools/types.ts
- src/devtools/useAtomsDebugValue.ts
- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
- src/urql/atomWithMutation.ts
- src/urql/atomWithQuery.ts
- src/urql/atomWithSubscription.ts
- src/utils/atomFamily.ts
- src/utils/atomWithObservable.ts
- src/utils/atomWithStorage.ts
- src/utils/splitAtom.ts
- src/valtio/atomWithProxy.ts
- tests/basic.test.tsx
- tests/items.test.tsx
- tests/utils/splitAtom.test.tsx
I didn't prefer interfaces because of the overload capability.
But, this isn't nice at all: https://tsplay.dev/mq132m
So, changing my mind...
close #1233
> refactor: prefer interface to type alias

- src/devtools/useAtomsSnapshot.ts
- src/devtools/useGotoAtomsSnapshot.ts
- tests/devtools/useAtomsSnapshot.test.tsx
- tests/devtools/useGoToAtomsSnapshot.test.tsx
This issue address this in #911 
> Maybe we should somehow return dependents too. (Provider's useDebugState does it)
> feat(breaking-change): return dependants with useAtomsSnapshot (v2)

- docs/api/babel.mdx
- docs/api/utils.mdx
- docs/guides/async.mdx
- docs/guides/core-internals.mdx
- docs/guides/debugging.mdx
- docs/guides/testing.mdx
- docs/integrations/query.mdx
- docs/utils/atom-with-storage.mdx
1) Fixed typo "embeded" to "embedded"
2) Fixed typo "identifer" to "identifier".
3) Fixed typo "limmited" to "limited".
4) Fixed typo "dependants" to "dependents".
5) Fixed typo "recursivly" to "recursively".
6) Fixed typo "seperate" to "separate".
7) Fixed typo "gastby" to "Gatsby".
8) Fixed typo "retreiving" to "retrieving".
9) Fixed typo "retreival" to "retrieval".
> docs: typo in some files

- src/devtools/useGotoAtomsSnapshot.ts
This addresses another task of #911 which tries to bring the versionedWrite ability to useGotoAtomsSnapshot (as it was in useAtomsDevtools).
> feat: versionedWrite in useGotoAtomsSnapshot

- src/core/atom.ts
```ts
// ts-error:
// Exported variable 'itmeSizeAtom' has or is using name 'WithInitialValue'
// from external module but cannot be named.ts(4023)
export const itmeSizeAtom = atom(16)
```
> fix(types): can not export atoms

- package.json
- src/xstate/atomWithMachine.ts
- yarn.lock
[Bug: atomWithMachine typescript error after updating xstate to version 4.29.0](https://github.com/pmndrs/jotai/issues/1000)
The internal typings are far from ideal, but this is how xstate achieves typing their [`useIdelInterpreter`](https://github.com/statelyai/xstate/blob/6badd2ba3642391bee640aa4914003ad57f2e703/packages/xstate-react/src/useInterpret.ts) without getting an error with `tsTypes` defined
> fix(xstate): atomWithMachine typescript error after updating xstate to version 4.29.0

- src/xstate.ts
- src/xstate/atomWithMachine.ts
- tests/xstate/atomWithMachine.test.tsx
The XState machine can be started with a default state and a custom passed state. This PR handles only the default one (as is the atom - doesn't handle hydration).
It is done by sending a jotai `RESET` in `send`:
```ts
import { RESET } from 'jotai/utils'
// ...
const [current, send] = useAtom(myMachineAtom);
// example usage of resetting machine by leaving a route in react-navigation:
useFocusEffect(
useCallback(
() =>
navigation.addListener('beforeRemove', () => {
send(RESET);
}),
[navigation, send],
),
);
```
Typescript will not complain as `typeof RESET` is added to the types of events that `send` my accept
> fix(xstate): Allow restarting a machine in a global atom

- .eslintrc.json
- src/core/atom.ts
- src/core/store.ts
- src/devtools/types.ts
- src/devtools/useAtomDevtools.ts
- src/devtools/useAtomsDebugValue.ts
- src/devtools/useAtomsDevtools.ts
- src/query.ts
- src/query/atomWithInfiniteQuery.ts
- src/query/atomWithQuery.ts
- src/urql/atomWithMutation.ts
- src/urql/atomWithQuery.ts
- src/urql/atomWithSubscription.ts
- src/utils/atomFamily.ts
- src/utils/atomWithObservable.ts
- src/utils/atomWithStorage.ts
- src/utils/splitAtom.ts
- src/valtio/atomWithProxy.ts
- tests/basic.test.tsx
- tests/items.test.tsx
- tests/utils/loadable.test.tsx
- tests/utils/splitAtom.test.tsx
following https://github.com/pmndrs/zustand/pull/1106
This reverts #1234 to some extent.
Exporting types is revisited. For example, `AtomFamily` is exported now. #1012
> fix(types): use TS interfaces only for public api

- docs/integrations/query.mdx
I had a project with existing integrations with `react-query` before importing `jotai` to the project.
Upon using `atomWithQuery` without this initialisation step, I realised that my existing functions which called `queryClient.invalidate(...)` did not result in `atomWithQuery`'s query invalidating. As a result, data was not refetched and the atom had stale data.
After browsing the discussions, I found the answer here https://github.com/pmndrs/jotai/discussions/500#discussioncomment-803421. The cause was because our functions were referencing different instances of `queryClient`
Seeing that this was a discussion thread, and that others might port in jotai into existing projects which already have `react-query` integrated, I thought it might be helpful to add this piece of documentation …
> docs(jotai/query): same query client initialisation

- docs/utils/atom-with-hash.mdx
It seems like a mistake in #879.
> docs(utils): fix atomWithHash options

- docs/advanced-recipes/custom-useatom-hooks.mdx
> docs: typo in documentation changed 'warp' to 'wrap'

- docs/utils/atom-with-storage.mdx
- src/utils/atomWithReset.ts
- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
- tests/utils/useResetAtom.test.tsx
Closes #1335 
- Created new type `StorageSetStateAction` which allows for the State setter's function to return `typeof RESET`
- Added conditional check to detect if returned `newValue` is `typeof RESET` after calling callback. If it is, run steps to reset storage
- Update `SetStateAction` callback union type from `type SetStateAction<Value> = Value | ((prev: Value) => Value)` to `type SetStateAction<Value> = Value | ((prev: Value) => Value) | typeof RESET` but this was cause affect all atom state setters. It seems only `atomWithStorage` / `atomWithHash` would benefit from this type, so I decided to create a type specifically for this util atom. 
- If possible, maybe we can derive types from `SetStateAction`, but I am relatively new to typescript and do not know of a way to do this
- An …
> feat(utils): support RESET with update function for atomWithStorage/atomWithHash/atomWithReset

- src/utils.ts
- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
close #1347 
I ended up with introducing a symbol and removing big try-catch completely.
(while I originally thought about throwing a symbol or something, returning a symbol should be cleaner.)
I had to fix a test for #949.
Also, did a tweak for `.subscribe` #1004, to work with non `defaultStorage`. (There was an issue/discussion which I don't remember.)
> fix(utils): avoid catching storage error in atomWithStorage

- src/utils/atomFamily.ts
- tests/utils/atomFamily.test.tsx
`shouldRemove` doesn't remove atoms correctly if `areEqual` is provided.
It's an edge case, but it can happen often if `createdAt` in `shouldRmove` is used and `param` isn't used.
> fix(utils/atomFamily): handle edge case with shouldRemove and custom equality function

- docs/api/devtools.mdx
- src/devtools/useAtomsSnapshot.ts
- src/devtools/useGotoAtomsSnapshot.ts
- tests/devtools/useAtomsSnapshot.test.tsx
- tests/devtools/useGoToAtomsSnapshot.test.tsx
This PR tries to follow the footsteps of the useAtomsDevtools for useAtomsSnapshot/useGotoAtomsSnapshot!
> refactor(devtools): silent useAtomsSnapshot/useGotoAtomsSnapshot in prod

- src/devtools/useAtomsDevtools.ts
Resolves #1356 
Since we have so common code between useAtomsDevtools and useAtomsSnapshot, we try to use the latter in the former. 
Note: This an exception, we don't usually use utils in themselves !
> refactor(devtools): use useAtomsSnapshot in useAtomsDevtools

- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
Fixes #1373
Added a condition to the if statement that already existed that, in addition to checking whether the global `window` object exists, also checks that `window.addEventListener` exists. Also added a simple test to prevent regression in the future.
I tested this in the project I first discovered the bug using yalc (since React Native doesn't support symlinks), and, other than a weird type issue where the `value` in `[value] = useAtom(atom)` shows as unknown, it doesn't throw an error now. I doubt my one-line change could have actually messed with the typings, but wanted to call it out for you to verify as the expert. 
Note: The beforeAll function in the added test looks a bit odd with the `;` in front but was added by prettier, probably to prevent the parentheses around `(window …
> fix(utils/atomWithStorage): Prevent createJSONStorage from adding subscribe method when window.addEventListener is not defined

- src/utils/atomWithStorage.ts
Seems like a regression in #1363 
Fixes #1377 
---
I wonder if there's a better way in general not only for SSR/SSG.
fwiw, #1373 is not SSR, but RN.
but, the goal of #1363 is not to hide exceptions, so we need to get feedback for "expected" usage.
> fix(utils/atomWithHash): do not cause error when location is not available

- package.json
- src/urql/atomWithMutation.ts
- src/urql/atomWithQuery.ts
- src/urql/atomWithSubscription.ts
- tests/urql/atomWithMutation.test.tsx
- tests/urql/atomWithQuery.test.tsx
- tests/urql/atomWithSubscription.test.tsx
- yarn.lock
close #1368 
This is a breaking change in `jotai/urql` for TypeScript users.
For JavaScript users, it wouldn't be breaking.
See also: https://github.com/FormidableLabs/urql/pull/2607
> breaking(types,urql): update @urql/core v6

- package.json
- src/core/atom.ts
- src/core/store.ts
- src/core/useAtom.ts
- src/core/useAtomValue.ts
- src/utils/loadable.ts
- src/utils/selectAtom.ts
- src/utils/waitForAll.ts
close #1398
We used have our custom `Awaited`, but it doesn't work with TS < 4.0.
This PR eliminates the custom one, and uses the built-in one available since TS >= 4.5.
For older versions, we patch with a limited (non-recursive) `Awaited` type.
> fix(types): patch awaited for ts < 4.5

- docs/integrations/query.mdx
While reading the documentation on getting started with React Query, I noticed that import was missing.
^ didn't run, as the change is md related.
> Add missing `queryClientAtom` import to the `React Query` guide

- src/query/atomWithQuery.ts
- tests/query/atomWithQuery.test.tsx
Fixes #1416 
- Create an observer just once for each `options`.
- Add a hack for `keepPreviousData`.
- Refactor to be similar to `jotai/urql` impl.
- `write` function no longer returns a promise.
> fix(query): create QueryObserver with initial options

- docs/guides/composing-atoms.mdx
- none
- fix the description in [Overriding default atom values](docs/guides/composing-atoms.mdx)
- By the way, the code below is simpler than the example in this document. Why do we need to check the type of `typeof newValue === 'function'` ?
```ts
const rawNumberAtom = atom(10.1) // can be exported
const roundNumberAtom = atom((get) => Math.round(get(rawNumberAtom)))
const overwrittenAtom = atom<number | null>(null)
export const numberAtom = atom(
(get) => get(overwrittenAtom) ?? get(roundNumberAtom),
(_, set, newValue: number | null) => set(overwrittenAtom, newValue)
)
```
> chore: fix the description in Overriding default atom values

- docs/utils/loadable.mdx
- none
- Fixed how variables are assigned when getting an asynchronous response using the loadable API in the sample docs.
- Since the response type is `[Awaited<Value>, never]`, we need to enclose the variable in square brackets. Or is it better to fix it with `useAtomValue`?
> chore: fix doc example in loadable api

- src/devtools/useAtomsDevtools.ts
- tests/devtools/useAtomsDevtools.test.tsx
Fixes #1445
This tries to disconnect devtools on unmount which fixes the issue.
> fix(devtools): double init call

- .github/workflows/test-old-typescript.yml
- tests/types.test.tsx
In https://github.com/pmndrs/zustand/pull/1348, I added a workflow to test against old ts versions. Let's follow it.
> chore(test): test with old typescript versions

- docs/guides/async.mdx
Fixes documentation that had grammatically incorrect sentence.
> chore(docs): duplicate verb in multiple tenses

- docs/api/babel.mdx
- src/babel/plugin-debug-label.ts
- src/babel/plugin-react-refresh.ts
- src/babel/preset.ts
- src/babel/utils.ts
- tests/babel/plugin-debug-label.test.ts
- tests/babel/plugin-react-refresh.test.ts
- tests/babel/preset.test.ts
Fixes #1414.
This PR adds support for custom atom names for the Babel plugins.
> feat(babel): Support custom atom names

- docs/advanced-recipes/large-objects.mdx
I think its meant to say `films` instead of `film` (Which doesn't exist as a key).
Fixes #.
> Fix docs mentioning incorrect key of data

- src/babel/utils.ts
Small fix to make sure custom atom names works for identifiers.
> fix(babel): Fix custom atom names for identifiers

- docs/integrations/query.mdx
I think this is self-explanatory. 
The first hook was introduced as `atomsWithQuery`, but then the other two are prefixed with `atomsWithTansack` (which is a typo too because it should be TanStack).
> fix(docs): Fix typos and inconsistent headings in TanStack Query page

- tests/babel/plugin-debug-label.test.ts
- tests/babel/plugin-react-refresh.test.ts
- tests/babel/preset.test.ts
Fixes https://github.com/pmndrs/jotai/pull/1480
The test case about custom atom names should test the node's initializer expression.
> test: custom atom names case

- CONTRIBUTING.md
not issues
I added information about yarn version.
This may not be common, but I didn't know why ci was failing
So how about adding some info about yarn version?
> docs: add info about yarn version

- docs/guides/async.mdx
Fixes problem mentioned in discussion #1589
Jotai atoms might start as sync atoms and later become async when provided with async value (Promise). Without explicit typing using sync atom as async does not typecheck in TypeScript. It's useful to add this information to documentation and describe a solution.
> docs: describe sync/async atoms creation in TypeScript

- docs/api/core.mdx
A quick change as discussed on chat to clarify that `useSetAtom()` is useful in general as a performance improvement.
> docs(core): clarify `useSetAtom`

- docs/advanced-recipes/custom-useatom-hooks.mdx
- docs/advanced-recipes/large-objects.mdx
- docs/guides/composing-atoms.mdx
> fix(docs): rename to jotai-optics

- docs/integrations/query.mdx
Just found this: https://twitter.com/shastri9999/status/1597840946804428803
> fix(docs): missing atom imports in query integration

- docs/integrations/trpc.mdx
[jotai-trpc](https://github.com/jotai-labs/jotai-trpc) is a third-party library to integrate [tRPC](https://trpc.io). This is the first version of docs. It only has an example for "query".
> docs: add trpc integration

- docs/integrations/relay.mdx
[jotai-relay](https://github.com/jotai-labs/jotai-relay) is a third-party library to integrate [Relay](https://relay.dev/). This is the first version of docs. It only has an example for "query".
> docs: add relay integration

- docs/integrations/cache.mdx
[jotai-cache](https://github.com/jotai-labs/jotai-cache) is a third-party library to add cache capability to atoms.
> docs: add cache integration

- src/vanilla/utils.ts
- src/vanilla/utils/unwrap.ts
- tests/vanilla/utils/unwrap.test.tsx
follow up #1515.
(this is still an unstable feature.)
> feat(vanilla): rename unwrapAtom to unwrap (v2 API)

- docs/guides/core-internals.mdx
Fixes #1619 
Fix small mistake in core-internals document.
> docs: fix code documentation in core-internals document

- docs/integrations/query.mdx
Whilst reading the `integration/query` docs, I noticed a couple of minor spelling mistakes.
* `Suspnse` should be `Suspense`
* `seperate` should be `separate`
> docs: spelling of `Suspense` and `separate`

- docs/guides/migrating-to-v2-api.mdx
- src/react/devtools/useGotoAtomsSnapshot.ts
- src/react/utils/useHydrateAtoms.ts
- src/vanilla/store.ts
When I worked on #1515, I was very skeptical about it. `restoreAtoms` is like a hack as public api. This PR make it dev-only. We may revisit it after v2 release, but this feels more comfortable and should make sense.
#1646 reminds me of this. Thanks.
> fix(vanilla): make restore atoms dev only (v2 API)

- docs/integrations/trpc.mdx
Update code block language to `ts` and `tsx` instead of `jsx`
> docs: fix code example format of trpc integration guide

- src/vanilla/store.ts
- tests/vanilla/dependency.test.tsx
> fix(vanilla): reading async atom twice before resolving (v2 API)

- readme.md
Optimized readme.md code format
- [x ] `yarn run prettier` for formatting code and docs
> docs: Optimized readme.md code format

- docs/integrations/urql.mdx
Update demo code of `jotai-urql (integration)`
The demo code sandbox shown in the doc is outdated, so updated with latest changes.
> fix: demo code sandbox of jotai-urql

- docs/guides/typescript.mdx
Add an example about the case access to the return type
https://github.com/pmndrs/jotai/discussions/1699
Add an example about the case access to the return type
> fix(docs): Update typescript.mdx

- docs/integrations/urql.mdx
I have added a new section in `jotai-urql` integration docs, Where it explains how to pass `urqlClient` to the jotai `provider`.
> docs: how to use urql client with the jotai provider.

- docs/guides/migrating-to-v2-api.mdx
Fixes English error in migration to v2 api doc
> Fix English error in migration to v2 api doc

- website/tailwind.config.js
This PR changes the Tailwind `hover` prefix behavior to apply only when supported by the device (laptop, desktop, etc).
> fix(website): hover only when supported by device

- docs/guides/initialize-atom-on-render.mdx
- docs/guides/migrating-to-v2-api.mdx
- docs/integrations/query.mdx
- docs/integrations/urql.mdx
- Mitigate misleading async atom usage in v2 (Looking at a tweet from @azu )
- Guide `useHydrateAtoms` in place of `createStore` for migrating from Provider's `initialValues` prop (Discussing with @sandren )
> fix(docs): migration guide about createStore usage

- website/src/pages/index.js
> docs: fix typo of useSetAtom

- docs/guides/migrating-to-v2-api.mdx
ref https://github.com/pmndrs/jotai/discussions/1751#discussioncomment-4890130
> fix(docs): add note about splitAtom in v2 migration guide

- src/vanilla/typeUtils.ts
- tests/vanilla/types.test.tsx
I'm still confused with `any` vs. `unknown`.
> fix(vanilla): type utils

- src/vanilla/store.ts
- tests/vanilla/dependency.test.tsx
No issue was created.
See: https://github.com/pmndrs/jotai/discussions/1761
When async derived atom is set immediately following an 'await' on get, it fails to get marked for re-calculation, so subsequent get will return the old value.
Included a unit test that has a minimal failure reproduction scenario, and a fix that makes the test pass.
> fix(vanilla): async derived atom not updated (race condition in an edge case)

- src/vanilla/atom.ts
- src/vanilla/utils/atomWithDefault.ts
- src/vanilla/utils/atomWithObservable.ts
- src/vanilla/utils/atomWithStorage.ts
- src/vanilla/utils/loadable.ts
- src/vanilla/utils/splitAtom.ts
- src/vanilla/utils/unwrap.ts
- tests/vanilla/basic.test.tsx
Add `debugPrivate` property to `atom` (Intended to be used by the core Jotai and other Jotai libraries to mark atoms used internally within other atoms as private)
> feat: add 'debugPrivate' flag to atom

- rollup.config.js
#1742 broke the if statement.
https://unpkg.com/browse/jotai@2.0.2/esm/vanilla.mjs
```js
if (((_a = import.meta.env) == null ? void 0 : _a.MODE) !== "production") {
```
It doesn't work with this: https://vitejs.dev/guide/env-and-mode.html#production-replacement
This PR should improve it, but unless `import.meta.env` is statically replaced, it doesn't help. (which is true for previous versions)
> fix(build): possibly improve ESM for production build

- docs/guides/testing.mdx
* There was no import for the `useHydrateAtoms` hook
* The countAtom was not being exported from the file.
> fix(docs): Added correct imports to testing docs page

- docs/tools/devtools.mdx
- Add documentation for UI-based Jotai Devtools
> docs(devtools): add docs for UI based devtools

- docs/integrations/query.mdx
Fixes https://github.com/jotaijs/jotai-tanstack-query/issues/29
clarifies that `statusAtom` in `atomsWithQuery` doesn't throw errors to Error Boundary. Feel free to update it if it has grammar issues.
> fix(docs/query): `statusAtom` doesn't pass errors to Error Boundary

- docs/guides/resettable.mdx
- docs/recipes/atom-creators.mdx
- docs/utilities/resettable.mdx
N/A
`useUpdateAtom()` had been deprecated since v2. Update the example to use the new API.
> docs: replace useUpdateAtom with useSetAtom

- website/gatsby-browser.js
- website/gatsby-shared.js
- website/gatsby-ssr.js
- website/src/pages/docs/{Mdx.slug}.js
- website/src/pages/index.js
Wrap Layout in wrapPageElement, preventing Layout unmount.
Before:
After:
> fix: website aside remount

- docs/guides/initialize-atom-on-render.mdx
The updated code is following [the migration guide](https://jotai.org/docs/guides/migrating-to-v2-api).
> docs(initialize-atom-on-render): migrate codesandbox code to v2

- src/babel/utils.ts
- tests/babel/plugin-debug-label.test.ts
- Add debug label support for third-party jotai libraries like `jotai-optics`, `jotai-location`, `jotai-form`, `jotai-cache`, `jotai-recoil`, etc.
> fix(babel): improve debug label support for third-party jotai libraries

- src/react/useAtom.ts
- src/react/useAtomValue.ts
- src/react/useSetAtom.ts
- tests/react/types.test.tsx
Fixes #1831
Draft. Lets iterate on solving this inference issue with `useAtom`.
> fix(react): atom type inference in hooks

- docs/guides/nextjs.mdx
https://github.com/pmndrs/jotai/discussions/1836
When creating `atomWithHash()` using Next13 the atom was not receiving any data when navigating using the router.  This was the result of changes to the router API in the latest release and is currently a planned feature.  To help clear up confusion in the website docs, I have added a section below the Sync with Router to advise caution when using with the latest NextJS version and links to the roadmap where more information on the feature can be found.
> docs(nextjs): :memo: added caution when using router in NextJS 13

- docs/utilities/storage.mdx
- src/vanilla/utils.ts
- src/vanilla/utils/atomWithStorage.ts
- tests/react/vanilla-utils/atomWithStorage.test.tsx
Fixes #1815
* **BREAKING CHANGE:** `SyncStorage` and `AsyncStorage` now receive `initialValue` as an argument to `getItem` and `subscribe`
* **BREAKING CHANGE:** Removed export `unstable_NO_STORAGE_VALUE`
* Updated `createJSONStorage` to correctly handle incoming `storage` events triggered by `removeItem` in another window
* Updated `createJSONStorage` to avoid attaching `storage` event handler when the storage is not browser storage (this happens on mount, so it shouldn't conflict with SSR)
* Added unit tests to cover both of the updates to `createJSONStorage` behavior.
* Updated mock "listeners" in unit tests to more correctly reflect browser storage behavior ([the `storage` event is not triggered by updates from the current window](https://developer.mozilla.org/en-US/docs/Web/API/Window …
> fix(atomWithStorage): handle RESET/removeItem from cross-tab storage updates

- src/react/utils/useHydrateAtoms.ts
- tests/react/utils/types.test.tsx
- tests/react/utils/useHydrateAtoms.test.tsx
Fixes #990
Currently `useHydrateAtoms` allows any unknown value to be passed for all atoms being hydrated. Instead this should be type safe and infer the type for the value(s) passed based on the atom.read function return type.
Cleaned up test title and removed duplicate test.
|     BEFORE      |      AFTER      |
|:---------------:|:---------------:|
| ![Screenshot 2023-04-27 at 12 09 19 PM](https://user-images.githubusercontent.com/525506/234938179-85d745ed-f534-4e11-8e3c-7ac94ca60f60.png) | ![Screenshot 2023-04-27 at 12 08 29 PM](https://user-images.githubusercontent.com/525506/234938218-bb9c6124-51a6-4bf6-b39e-4548f50a599f.png) |
| ![Screenshot 2023-04-27 at 12 09 36 PM](https://user-images.githubusercontent.com/525506/234938262-a5c374fd-7f71-43db-bf5d-12371f9b2fe2.png) | ![Screenshot …
> fix(react): Infer useHydrateAtoms value types from atom.read ReturnType

- docs/guides/initialize-atom-on-render.mdx
Just some minor typos.
Check List
> docs: fix typos on "initialize atom on render"

- docs/utilities/storage.mdx
Fixes #
setItem argument missing from storage example
> fix(docs): setItem argument missing from storage example

- docs/recipes/custom-useatom-hooks.mdx
> docs: fix typo in docs/recipes/custom-useatom-hooks

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Fixes #1925
Do not recreate the cancelable promise when the promise did not change
> fix(vanilla): Stable promise

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Fixes #1956
When the core is re-implemented in v2, we missed something for dependency (dependent) atoms re-calculation. In v1, it was fully pull based. In v2, it's pull and push. It tries to eagerly bail out. There was a regression and this should fix it.
(That brings me to a further refactoring. Can it be `dependents` in atom state instead of `dependencies`?? Let's explore it in the future.)
> fix(vanilla): update atoms with tree structure dependencies (reggression from v1)

- src/react/useAtomValue.ts
- src/vanilla/store.ts
- src/vanilla/utils/atomWithStorage.ts
Fixes #1963 
Values from outside library should work with PromiseLike (= thenable).
> fix: prefer PromiseLike where appropriate

- website/src/pages/index.js
Fixes missing import in SSR example for Next
Fixes #1979 
Adds missing import statement in SSR example for Next.
> website: Update index.js

- rollup.config.js
> fix(build): mode env for "import" condition"

- docs/utilities/ssr.mdx
- src/react/utils/useHydrateAtoms.ts
- tests/react/utils/useHydrateAtoms.test.tsx
The useHydrateAtom discussion has been live since August of 2021 in https://github.com/pmndrs/jotai/discussions/669.
We found a use case within our project that required a rehydration after a specific event. We had to manually rely on conditional useEffect actions to manually update the store rather than hydrating back from a fully reset SSR page. After review, a forceHydration option meets that requirement and a lot of the cases mentioned within that option discussion.
> feat(utils/useHydrateAtoms) - Optionally rehydrate with force hydrate

- src/vanilla/utils/atomWithStorage.ts
This is to fix (partially revert) the change in #1967.
Atom values are guaranteed to be Promise instead of PromiseLike, and this gives more interoperability with other utils.
> fix(utils): revert atomWithStorage typing

- src/vanilla/utils/unwrap.ts
- tests/vanilla/utils/types.test.tsx
- tests/vanilla/utils/unwrap.test.ts
Previously, we need to wrap a sometime async atom to be full async.
https://github.com/pmndrs/jotai/discussions/1988#discussioncomment-6193452
> fix(utils): improve unstable_unwrap for sometimes async atom

- docs/basics/concepts.mdx
- docs/guides/debugging.mdx
- docs/guides/performance.mdx
- docs/guides/react-native.mdx
The React docs moved to a new domain. This PR updates the URLs in the docs
> fix(docs): link either to new react docs or legacy docs

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Fixes #2014 
It's a regression from v1. It now checks atom values.
> fix(vanilla): bail out recomputing with the same value

- readme.md
read-only atoms, read-write atoms, and write-only atoms are all derived atoms.
> fix(readme): clarify write-only atoms are derived atoms

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
#1966 
Remove the dev-only signature that is deprecated in #1966.
> breaking: remove deperecated dev-only methods

- src/vanilla/store.ts
https://github.com/pmndrs/jotai/discussions/2044#discussioncomment-6616176
Follow-up #2049
We should warn only when the default store is used.
> fix(vanilla): improve warning message for multiple instances

- docs/utilities/async.mdx
> docs: fix typo

- CONTRIBUTING.md
Fixes # (Include the issue number here if applicable)
This PR addresses a typo in the `contributing.md` file. The incorrect yarn command `yarn run build:watch` has been corrected to `yarn run build-watch`. This change ensures that contributors are using the correct command as intended.
> Fix yarn command in contributing.md

- CONTRIBUTING.md
- package.json
- yarn.lock
Fixes #
This pull request updates the coverage provider from the deprecated "c8" to the new default "v8" as required by Vitest. The change aligns the project with the new standard and avoids the deprecated warning that appeared when running `yarn test`. 
More information can be found in the related Vitest pull request: [vitest-dev/vitest/pull/3339](https://github.com/vitest-dev/vitest/pull/3339).
> Update Coverage Provider from "c8" to "v8" in Vitest

- src/vanilla/utils/splitAtom.ts
- tests/react/vanilla-utils/splitAtom.test.tsx
Fixes https://github.com/pmndrs/jotai/discussions/2079
As agreed during the discussion, `set` should not be called when an item remains unmodified.
> fix(utils): Do not set a splitted atom when not actually modified

- docs/integrations/location.mdx
1. https://github.com/jotaijs/jotai-location/pull/4
2. https://github.com/jotaijs/jotai-location/pull/1
3. https://github.com/jotaijs/jotai-location/pull/13
1st PR added `setHash` and deprecated `replaceState` option of `atomWithHash`
2nd PR removed the `delayInit` option
3rd PR removed the deprecated `replaceState` option
this PR updates the docs to reflect those 3 changes
> docs: update location integration docs

- src/vanilla/store.ts
- tests/react/vanilla-utils/atomWithStorage.test.tsx
- tests/vanilla/store.test.tsx
> fix(vanilla): should recompute state after onMount

- src/vanilla/utils/atomWithStorage.ts
Related to https://github.com/pmndrs/jotai/pull/1375. In other environments (React Native in my case) `window.addEventListener` may be polyfilled, but `window.Storage` is not, so `instanceof window.Storage` fails.
`storage.subscribe` should only be defined if `window.Storage` is available in the environment.
> fix(utils/atomWithStorage): Prevent createJSONStorage from adding subscribe method when window.Storage is not defined

- docs/recipes/atom-with-broadcast.mdx
I split one long sentence into two sentences to make the description easier to read.
> docs: fix atomWithBroadcast description

- docs/integrations/urql.mdx
I keep forgetting that jotai-urql github repo isn't linked in the docs unlike jotai-tanstack-query, and it bothered me 😄
> docs: add urql and jotai-urql description. add jotai-urql github repo link

- docs/utilities/callback.mdx
Update the `useAtomCallback` documentation.
The docs were for Jotai v1; update for v2. The change is that the callback function passed to `useAtomCallback` no longer returns a Promise; it just returns the atom value.
@dai-shi I forked the CodeSanbox example [here](https://codesandbox.io/s/react-typescript-forked-95gxnt), removing the `await` that is no longer needed. However I wasn't sure how to update the CodeSanbox link (id) in the docs.
Fixes #2149 
Update the `useAtomCallback documentation for v2.
> Fix documentation for useAtomCallback.

- docs/integrations/valtio.mdx
Issue https://github.com/jotaijs/jotai-valtio/issues/4
Introduce a new section in the  documentation
to describe the functionality, use-cases, and examples for the new  API in the jotai-valtio integration library.
> docs(jotai-valtio): add  API section to docs

- docs/integrations/immer.mdx
- docs/integrations/valtio.mdx
Resolves: https://github.com/pmndrs/jotai/discussions/2171
Update the inline and codesandbox examples for Immer and Valtio to more accurately and clearly showcase their functionalities.
> doc: Update examples for Immer and Valtio

- docs/integrations/effect.mdx
doc: Add README for Jotai's Effect utility
- Introduce documentation for the Effect utility in Jotai.
- Provide a brief description and usage of the Effect utility.
- Include installation instructions for jotai-effect.
- Detail the `atomEffect` utility function, including parameters, usage, and advanced behaviors.
- Offer insights and examples on `atomEffect` behavior like cleanup functions, resistance to infinite loops, execution timing, batching updates, conditional running, idempotency, and dependency management.
> doc: Add README for Jotai's Effect utility

- docs/integrations/effect.mdx
Remove extra title in jotai-effect doc
> bug: remove extra title in jotai-effect doc

- docs/integrations/effect.mdx
Clarifies the distinction between useEffect and atomEffect.
https://x.com/lockr07/status/1712303803121139756?s=20
> doc: Fix CodeSandbox example and add 'Comparison with useEffect' section to jotai-effect doc

- docs/guides/nextjs.mdx
- docs/integrations/location.mdx
https://github.com/jotaijs/jotai-location/pull/24
> doc: Updated nextjs guide and useAtomWithHash docs on useAtomWithHash and replaceState

- docs/integrations/effect.mdx
https://github.com/jotaijs/jotai-effect/discussions/10
- use caution when using async atom-effects
- improve language on comparison with useEffect
> doc: update atom-effect docs

- docs/integrations/effect.mdx
https://github.com/jotaijs/jotai-effect/discussions/10
Given the caveats of managing atom dependencies with async effects, it will be best to deprecate support for async effects.
> Doc atom effect no async

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Fixes #2168 
- [ x] `yarn run prettier` for formatting code and docs
> fix(vanilla): avoid re-computing unmounted derived atoms in an edge case

- src/vanilla/store.ts
- tests/react/async.test.tsx
- tests/react/async2.test.tsx
- tests/vanilla/store.test.tsx
https://github.com/pmndrs/jotai/discussions/2192
https://github.com/pmndrs/jotai/issues/2191
Adds tests for the issue linked above.
A primitive atom (`atomP`) exists and has a value (`valueP`)
An async atom (`atomA`) gets the value (`valueAP`) from atomP and then has a delay (`delayA`) before returning the value from atomP.
A derived async atom (`atomB`) gets the value (`valueBP`) from atomP and after a microtask or greater delay (`delayB`) it gets the value (`valueBA`) from atomA.
The bug requires delayB < delayA.
So,
- atomP is a synchronous dependency of atomA and atomB
- atomA is an asynchronous dependency of atomB
After all atoms mount,
atomP is changed twice with a delay (`delayC`) less than delayA.
This first multi-change proceeds nominally. ✅
atomP is then changed twice again with …
> fix(vanilla): deal with promise resolving race condition

- docs/core/atom.mdx
- src/vanilla/atom.ts
Discussed in Poimandres Discord server
Add warning for setSelf about the internal use.
> docs: add a warning for setSelf

- docs/integrations/effect.mdx
Update jotai-effect docs:
- include section on async iffe
- clean up wording, simplify examples, fix mistakes
> docs(effect): add async section and clean up wording

- src/vanilla/utils/unwrap.ts
- tests/vanilla/utils/unwrap.test.ts
Fixes #2214
Fixed to carry over previous values
> fix(utils): unwrap may not return previous value

- src/react/utils/useHydrateAtoms.ts
Just found a tiny issue for precise  typing.
> fix(utils): useHydrateAtoms type

- tests/react/vanilla-utils/splitAtom.test.tsx
When the `before` is unspecified for the first item, it is being moved to the end of the list.
> test(splitAtom): moving first item to the end

- docs/core/atom.mdx
Fixes https://github.com/pmndrs/jotai/discussions/2268
> docs: update `atom.mdx`

- docs/guides/composing-atoms.mdx
Fixes #2281 
Add early return in dispatchAtom example.
> docs: fix dispatchAtom example

- docs/extensions/query.mdx
Related: https://github.com/jotaijs/jotai-tanstack-query/pull/45
> docs: update tanstack query integration documentation to the new api

- src/vanilla.ts
- src/vanilla/atom.ts
- src/vanilla/utils/atomWithReset.ts
Fixes #2303 
Changed return type of `atomWithReset()`,  
``` typescript
return anAtom as WritableAtom<Value, [Update], void>
```
to
``` typescript
return anAtom as WritableAtom<Value, [Update], void> & WithInitialValue<Value>
```
> fix(utils): add init property to the return type of atomWithReset

- docs/extensions/cache.mdx
- docs/extensions/effect.mdx
- docs/extensions/immer.mdx
- docs/extensions/location.mdx
- docs/extensions/optics.mdx
- docs/extensions/query.mdx
- docs/extensions/redux.mdx
- docs/extensions/relay.mdx
- docs/extensions/scope.mdx
- docs/extensions/trpc.mdx
- docs/extensions/urql.mdx
- docs/extensions/valtio.mdx
- docs/extensions/xstate.mdx
- docs/extensions/zustand.mdx
- docs/guides/nextjs.mdx
- docs/tools/devtools.mdx
It's 2024, and we can't list all npm alternatives. Let's simplify.
> chore(docs): show only npm install

- docs/tools/devtools.mdx
Essentially adds another example for the setup of Jotai Devtools in a React project (with Vite). More convenient than searching for it, like in my case.
> feat(docs): add devtools setup example for react+vite projects

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Fixes #2314
I'm sorry about the previous PR.
Changed evaluation of canUnmountAtom in mountDependencies function after mountAtom.
> fix(vanilla): should mount once with atom creator atom

- docs/utilities/storage.mdx
- src/vanilla/utils/atomWithStorage.ts
#2321
Support `reviver` and `replacer` options for JSON parse and stringify.
> feat(utils): createJSONStrage options

- docs/recipes/atom-with-listeners.mdx
> docs: fix atomWithListeners example

- src/vanilla/store.ts
- tests/react/async.test.tsx
- tests/vanilla/dependency.test.tsx
https://github.com/pmndrs/jotai/issues/2348
Atoms having an onMount function will remount on another atom recalculation.
Please see the following example below:
countAtom will remount when anotherAtom is incremented.
```ts
const countAtom = atom(0)
countAtom.onMount = () => {}
const anotherAtom = atom(0)
const derivedAtom = atom((get) => {
void get(countAtom)
})
const effectAtom = atom((get) => {
return Promise.resolve().then(() => {
get(derivedAtom)
get(anotherAtom)
})
})
```
Expected behavior is that countAtom should not remount when anotherAtom increments.
- [o] `yarn run prettier` for formatting code and docs
> fix: atoms should not remount on recalculations (with async dependencies)

- src/vanilla/utils/atomWithStorage.ts
- tests/react/vanilla-utils/atomWithStorage.test.tsx
Fixes downstream issue for https://ui.shadcn.com/
It crashes when cookies are disabled with this exception:
On Firefox accessing the property localStorage of window results in a `DOMException: The operation is insecure.`
This PR will handle this case gracefully and fall back to providing no storage implementation. This should be fine as we cannot store anything in a cookie-free browser.
> fix(utils/atomWithStorage): defaultStorage with disabled local storage crashes on mount

- src/vanilla/atom.ts
- src/vanilla/store.ts
supersedes #2353
- introduce `atom.unstable_is`
- make default `read` & `write` functions stable
> feat(vanilla): customizable atom.unstable_is

- docs/extensions/effect.mdx
Add section for recurse api and clean up wording
- [o] `yarn run prettier` for formatting code and docs (prettier updates unrelated files)
> docs(effect): add section for recurse api and clean up wording

- src/react/useAtom.ts
- src/react/useSetAtom.ts
- src/vanilla/atom.ts
I modified the `Args` type, which was defined in several places, to be uniform.
> refactor: modified Args type

- src/vanilla/store.ts
- src/vanilla/typeUtils.ts
N/A
Hi. I've been working with @edkimmel on performance improvements to our app. It's a React Native ecommerce app that heavily relies on Jotai for managing most state and data. A hotspot that stood out recently was `recomputeDependents`—that's how Eddie identified the Hermes memory leak (https://github.com/pmndrs/jotai/discussions/2355) as a source of our problems.
Even with Eddie's workaround in place for that memory leak, we still found that `recomputeDependents` was very slow for us, so we took a closer look at what `recomputeDependents` is doing. It's something like this:
* loop1 is `O(n*m)` where `n` is the number of atoms and `m` is the number of dependency edges.
* loop2 is `O(n*n*m)` because it does the same thing as loop1 but also iterates over the `dependencyMap` for each …
> Improve performance of recomputeDependents

- src/vanilla/store.ts
Fixes https://github.com/jotaijs/jotai-scope/issues/21
Here `isSelfAtom` should not be used as it could lead to unexpected cache.
> fix(vanilla): fix unexpected cache in jotai-scope

- docs/extensions/effect.mdx
Updates webside docs for jotai-effect.
- adds section for `get.peek`
- clean up wording
- [o] `yarn run prettier` for formatting code and docs
> docs(effect): add section for get.peek api and clean up wording

- docs/utilities/storage.mdx
Fixes https://github.com/pmndrs/jotai/issues/2240 confusion
Clarify that getOnInit is false by default and can be set to true in an SPA to get the stored value instead of the initial value.
`yarn run prettier` caused 100 invisible changes so I didn't commit the result.
> docs: clarify getOnInit being false

- .livecodes/react.json
https://github.com/pmndrs/jotai/pull/2386#issuecomment-1937380333
> fix livecodes template

- docs/recipes/atom-with-toggle-and-storage.mdx
- docs/recipes/atom-with-toggle.mdx
- docs/recipes/use-atom-effect.mdx
Adds a doc for useAtomEffect under the doc [Custom useAtom hooks](https://jotai.org/docs/recipes/custom-useatom-hooks).
> docs(effect): add recipe for useAtomEffect

- docs/tools/devtools.mdx
- Document DevTool's new position prop (https://github.com/jotaijs/jotai-devtools/pull/118)
> docs: add DevTool's new position prop

- src/react/useAtom.ts
- tests/react/types.test.tsx
This has been asked several times. Hope this doesn't break some usages.
> fix(types): useAtom with one type argument for primitive atoms

- rollup.config.js
https://github.com/pmndrs/jotai/issues/48
Jotai causes a very hard to debug syntax error in browsers that don't support ES2019. I tracked down the issue to the two `catch` blocks that use [Optional catch Binding](https://www.javascripttutorial.net/es-next/optional-catch-binding). Optional catch Binding was introduced in ES2019 and is not supported in Chrome 65 and older. This PR fixes that.
Browser support: https://caniuse.com/mdn-javascript_statements_try_catch_optional_catch_binding
> build: change rollup target to ES2018

- website/src/components/menu.js
Fixes #2425
The mobile menu was hidden using `opacity: 0` which doesn't hide it for keyboard users and screen readers and also breaks scrolling of the navigation in Safari.
The menu is no properly hidden when closed and on desktop. The `opacity` is still used for the transition.
> fix(website): hide menu overlay properly

- docs/guides/using-store-outside-react.mdx
- #263
Added docs to explain how to interact with atoms outside React
This Codesandbox is used in the example: https://codesandbox.io/p/sandbox/practical-bardeen-2jvynm?file=%2Fsrc%2FApp.tsx%3A16%2C5
> docs: using createStore to interact with atoms outside React 

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Sorry for the onslaught of PRs, I believe this one to be an actual fix to a regression caused by the #2396 refactor
For this bug to occur a few things have to happen:
1. An atom that we wish to update indirectly, e.g.
```ts
const emailAtom = atom('user@example.com')
```
2. An atom that simply writes to the atom above in its write function, e.g.:
```ts
const updateEmailAtom = atom(null, (_get, set, value: string) => set(emailAtom, value.trim()))
```
3. An atom that executes the above atom asynchronously, e.g.:
```ts
const initializeAndVerifyAtom = atom(null, async (_get, set, fields: FormFields) => {
const email = fields.email
await verifyEmail(email)
// this write is no longer sync, so should be flushed immediately, but the
// actual atom that will get set (emailAtom) thinks it is being …
```
> fix(vanilla): store should flush pending write triggered asynchronously and indirectly

- src/vanilla/utils/atomWithStorage.ts
https://github.com/pmndrs/jotai/pull/2447#issuecomment-1991109294
createStorage caches the last value, so this should be fine for most cases.
> fix(utils): atomWithStorage to always run onMount

- src/vanilla/store.ts
In my pursuit to understand the store implementation better, I found a few places where the code seems redundant (either because the check fails/succeeds before, likely unreachable, or the code is handling an undefined case even though the function is only called when the value is defined).
Changes:
- `canUnmountAtom` was being called at every call site of `unmountAtom`, so to reduce the risk of unmounting an atom prematurely at some call site by mistake, I moved the check into the function.
- Renamed `unmountAtom` to `tryUnmountAtom` to better reflect the new behavior
- Moved `canUnmountAtom` closer to the call site (`tryUnmountAtom`) to increase code legibility.
- Made `mountAtom` idempotent for already mounted atoms, which removed most "is this already mounted" checks.
- (needs …
> refactor(vanilla): moved (un)mount guards into their respective functions. (suggestion)

- src/react/Provider.ts
- src/react/utils/useResetAtom.ts
- src/vanilla/store.ts
- src/vanilla/utils/atomWithObservable.ts
- src/vanilla/utils/atomWithReset.ts
- src/vanilla/utils/freezeAtom.ts
> fix: avoid slow types

- src/babel/plugin-debug-label.ts
While working on #2479, I noticed depending on `node` isn't a good idea.
> fix(babel): do not depend on path

- src/vanilla/utils/atomWithLazy.ts
based on #2465 
While woking on #2479 and enabling CJS tests, I noticed that with the current transpilation target, it expands `{...}` and makes the test to fail. So, let's refactor it to be compatible with transpiration.
> refactor atomWithLazy

- src/vanilla/utils/freezeAtom.ts
- tests/react/vanilla-utils/freezeAtom.test.tsx
None
Extends the `freezeAtomCreator` test to unveil a bug
> fix(utils): improve freezeAtom and freezeAtomCreator

- tests/react/types.test.tsx
Fixes #2499
We had test for primitive atoms, but test for read-only atoms were missing.
> chore(tests): add test for useAtom types

- website/src/components/code.js
- website/src/components/main.js
- website/src/components/wrapper.js
When the content in the main container is too short, the container will shrink, causing layout flickering.
Setting `flex-grow` on main can solve this problem, always keeping main to fill its parent container.
https://jotai.org/docs/utilities/reducer
https://github.com/pmndrs/jotai/assets/28357731/cc0462e8-f97e-4019-8c0c-ca1c82b41e7c
Adding the notranslate class to the code block component can prevent the code text from being translated by Google.
> Fix document layout flickering.

- docs/utilities/ssr.mdx
- website/src/components/stackblitz.js
Fixes #2516 
As per #2516, here's my first PR to migrate Codesandbox examples to Stackblitz. (This is my personal Github acc). While copying this particular SSR example, I found it quite irrelevant and failed to demonstrate the [`useHydrateAtoms`](https://jotai.org/docs/utilities/ssr#usehydrateatoms) which the example is placed at. Can I make change to the example to make it relevant and useful?
> Docs: stackblitz migration

- docs/guides/nextjs.mdx
Migrate Codesandbox demo embeds in Next.js page to Stackblitz
- Clock demo: https://stackblitz.com/edit/stackblitz-starters-nsugnt
- HN demo: https://stackblitz.com/edit/stackblitz-starters-cnz9lg
> docs: migrate Codesandbox embeds in Next.js page to Stackblitz

- tests/react/types.test.tsx
`TypeEqual` util is required to test them properly.
> chore(tests): fix useAtom and useSetAtom type tests

- src/vanilla/store2.ts
- tests/vanilla/memoryleaks.test.ts
- tests/vanilla/storedev.test.tsx
> fix: memory leaks in store2

- tests/vanilla/memoryleaks.test.ts
https://github.com/pmndrs/jotai/issues/2477 
Fails with store and store2
> fix(tests): add memory leak tests

- src/vanilla/store2.ts
I somehow thought this method was necessary. just silly.
> chore(store2): remove meaningless dev method

- src/vanilla/store.ts
- tests/react/dependency.test.tsx
Fixes #2565
The issue only occurs with `store.ts` and `react@18`.
`store2` doesn't have the issue and neither `react@19-rc`.
I'm not very confident why this change fixes the issue, so there might remain other issues somewhere else.
> fix(vanilla): fix store.ts for an edge case

- docs/core/use-atom.mdx
Remove duplicated section about useAtom inside the signature section and update the wording to improve clarity
Fixes #
> Update core/useAtom docs

- src/vanilla/store2.ts
- tests/vanilla/storedev.test.tsx
- Adds `dev4_get_mounted_atoms` to return Iterable list of mounted atoms
> feat(store2): add dev4_get_mounted_atoms

- docs/extensions/urql.mdx
- docs/guides/initialize-atom-on-render.mdx
- tests/react/async2.test.tsx
> chore: fix some comments

- website/src/components/button.js
Fixes #
While toggling the theme, the sidebar shrunk in size when on the dark theme.
> fix border for buttons - dark theme

- docs/basics/concepts.mdx
- docs/utilities/ssr.mdx
- website/src/components/stackblitz.js
Fixes #
Just added some English fixes.
> English updates.

- src/vanilla/store.ts
- src/vanilla/store2.ts
- tests/react/abortable.test.tsx
- tests/vanilla/store.test.tsx
Fixes #2625
@dai-shi agreed that not aborting promises on unsubscription was the best solution here.
When added to the continuable/cancellable promise idiom, it makes quite a lot of sense. Only abort the promise if you can replace it with another one.
I added the behaviour to store and store2
> fix: do not abort atoms on unmount

- docs/guides/testing.mdx
- tests/react/async.test.tsx
- tests/react/async2.test.tsx
- tests/react/basic.test.tsx
- tests/react/items.test.tsx
- tests/react/onmount.test.tsx
- tests/react/optimization.test.tsx
- tests/react/useAtomValue.test.tsx
- tests/react/useSetAtom.test.tsx
- tests/react/utils/useAtomCallback.test.tsx
- tests/react/utils/useHydrateAtoms.test.tsx
- tests/react/utils/useReducerAtom.test.tsx
- tests/react/utils/useResetAtom.test.tsx
- tests/react/vanilla-utils/atomFamily.test.tsx
- tests/react/vanilla-utils/atomWithDefault.test.tsx
- tests/react/vanilla-utils/atomWithObservable.test.tsx
- tests/react/vanilla-utils/atomWithReducer.test.tsx
- tests/react/vanilla-utils/freezeAtom.test.tsx
- tests/react/vanilla-utils/loadable.test.tsx
- tests/react/vanilla-utils/selectAtom.test.tsx
- tests/react/vanilla-utils/splitAtom.test.tsx
We've migrated to user-event for some tests, and this does it for all possible ones.
> chore(tests, docs): prefer user-event

- .github/workflows/compressed-size-action.yml
- .github/workflows/lint-and-type.yml
- .github/workflows/livecodes-preview.yml
- .github/workflows/publish.yml
- .github/workflows/test-multiple-builds.yml
- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
Upstream: https://github.com/pnpm/action-setup/issues/135#issuecomment-2206861174
> ci: fix pnpm setup

- tests/vanilla/store.test.tsx
Adds test for unstable_derive store api.
```
a, b, c(a), d(c), e(d + b)
S1[d]: a0, b0, c0(a0), d1(c1(a1)), e0(d1(c1(a1)) + b0)
```
This new case tests both read and write for the combination of scoped and unscoped derived atoms indicated by the above configuration.
1. `a` and `b` are primitive atoms.
1. `c`, `d`, and `e` are derived atoms.
1. `c` depends on `a`, `d` depends on `c`, and `e` depends on `d` and `b`.
1. In the derivedStore (deriStore), only `d` is explicitly scoped.
1. Because `d` is explicitly scoped, its dependency `c` is implicitly scoped.
1. Implicitly scoped `c`'s dependency `a` is also implicitly scoped.
1. Because `e` is not scoped, `e` can read both explicitly scoped and not scoped dependencies `d` and `b`.
> add test for unstable_derive

- src/vanilla/atom.ts
```js
const anAtom = atom(0)
anAtom.debugLabel = 'countAtom'
console.log(anAtom);
// dev: 'atom1:countAtom'
// prod: 'atom1'
```
> atom toString includes debugLabel in dev mode

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Fix #2658 
Add test for "Unmount an atom that is no longer dependent within a derived atom (#2658)" and fix.
> fix(core): Unmount an atom that is no longer dependent within a derived atom

- src/vanilla/atom.ts
- tests/vanilla/types.test.tsx
> fix(types): add undefined initial value to Atom definition

- docs/extensions/query.mdx
Wonka has been removed as a peer dependency from jotai-tanstack-query as part of https://github.com/jotaijs/jotai-tanstack-query/pull/84. This PR is to update the documentation.
> docs: (jotai-tanstack-query) remove wonka as a peer dependency

- docs/utilities/storage.mdx
> docs: remove redundant parentheses

- src/vanilla/utils/atomFamily.ts
- tests/vanilla/utils/atomFamily.test.ts
idea1: https://github.com/pmndrs/jotai/pull/2678
idea2: https://github.com/pmndrs/jotai/pull/2679
idea3: https://github.com/pmndrs/jotai/pull/2681
idea4: https://github.com/pmndrs/jotai/pull/2683
Fixes #2056
Fixes https://github.com/jotaijs/jotai-scope/issues/50
jotai-scope is trying to support scoping atomFamily.
```jsx
const fooFamily = atomFamily((id) => atom(id))
<ScopedProvider atomFamilies={[fooFamily]}>{children}</ScopeProvider>
```
This PR demonstrates one approach in which the atomFamily supports `getParams` and `unstable_listen`.
The following pseudo code represents logic that would live in jotai-scope.
```js
function handleChange({ type, atom }) {
if (type === 'CREATE') {
atomSet.add(atom)
} else {
atomSet.delete(atom)
}
}
for (const atomFamily of atomFamilies) { …
```
> feat(utils): atomFamily supports getParams and unstable_listen api

- docs/recipes/atom-with-broadcast.mdx
None
- The old code used the library's old TypeScript API. This update fixes it.
> docs(atom-with-broadcast): update example code to work with TypeScript

- docs/basics/functional-programming-and-jotai.mdx
- readme.md
Fixes #2724
Jotai atoms are monads. This is a compelling reason to choose Jotai, so it should be mentioned in the README and in documentation.
> Mention connections to functional programming in README and docs

- docs/basics/functional-programming-and-jotai.mdx
Fixes #2724
Show some examples of `sequence` to expand on advantages of seeing atoms as monads. Also add a list of other good resources to look at for monads.
> docs(functional): cover sequence

- docs/extensions/effect.mdx
Updates docs for jotai-effect.
- Adds docs for a new api `withAtomEffect`
> feat(docs): update docs for jotai-effect

- tests/vanilla/unstable_derive.test.tsx
1. derived atom with subscribe
```js
/**
* a, b(a)
* S1[a]: a1, b0(a1)
*/
```
1. derived atom shares same implicit
```js
/**
* a, b(a), c(a), d(a)
* S1[b, c]: a0, b1(a1), c1(a1), d0(a0)
*/
```
2. inherited atoms
```js
/**
* a, b, c(a + b)
* S1[a]: a1, b0, c0(a1 + b0)
* S2[ ]: a1, b0, c0(a1 + b0)
*/
```
3. inherited atoms use explicit in current scope
```js
/**
* a, b, c(a + b)
* S1[c]: a0, b0, c1(a1 + b1)
* S2[a]: a0, b0, c1(a2 + b1)
*/
```
4. uses implicit at any distance
```js
/**
* a, b(a), c(b), d(c), e(d)
* S1[a]: a1, b0(a1), c0(b0(a1)), d0(c0(b0(a1))), e0(d0(c0(b0(a1))))
* S1[b]: a0, b1(a1), c0(b1(a1)), d0(c0(b1(a1))), e0(d0(c0(b1(a1))))
* S1[c]: a0, b0(a0), c1(b1(a1)), d0(c1(b1(a1))), e0(d0(c1(b1(a1))))
* S1[d]: a0, b0(a0), c0(b0(a0)), d1(c1(b1(a1))), e0(d1(c1(b1(a1))))
* S1[e]: …
```
> Fix/unstable derive - add more tests

- tests/vanilla/utils/atomWithReset.test.ts
Add unit test for src/vanilla/utils/atomWithReset.ts
> :white_check_mark: test: add unit test for atomWithReset utility

- tests/vanilla/dependency.test.tsx
This pull request enhances the test suite for Jotai's dependency management, particularly focusing on complex scenarios. The following improvement has been made:
1. **Complex Dependency Chains**
- Introduced a test case that verifies Jotai's ability to handle and update complex chains of derived atoms, including async derivations.
- **Multi-level Derivations**: Verifies that updates properly propagate through multiple levels of derived atoms, including async operations.
Appreciated for having me your time on reviewing changes.
> test(dependency): Improve test coverage

- docs/utilities/ssr.mdx
Fixes  [#2470#discussioncomment-10838165](https://github.com/pmndrs/jotai/discussions/2470#discussioncomment-10838165)
This PR adds a note for `useHydrateAtoms` docs to emphasize its client code usage.
Preview:
> docs: add a note for useHydrateAtoms client code usage

- docs/utilities/storage.mdx
Just a bit of documentation I thought was a tad misleading. Reworded
> docs: improve AsyncStorage notes wording

- docs/recipes/use-atom-effect.mdx
Hello :)
Just a small PR to fix a little typo in the dependency array.
Thank you for the library :*
> docs: Fix typo in useAtomEffect doc

- tests/react/vanilla-utils/atomWithDefault.test.tsx
Added unit test with missing scenario of setting `atomWithDefault` with primitive value. Provides 100% of code coverage for this utility.
> test: improve code coverage for atomWithDefault

- tests/react/abortable.test.tsx
- tests/react/async.test.tsx
- tests/react/async2.test.tsx
- tests/react/basic.test.tsx
- tests/react/dependency.test.tsx
- tests/react/error.test.tsx
- tests/react/items.test.tsx
- tests/react/onmount.test.tsx
- tests/react/optimization.test.tsx
- tests/react/provider.test.tsx
- tests/react/transition.test.tsx
- tests/react/types.test.tsx
- tests/react/useAtomValue.test.tsx
- tests/react/useSetAtom.test.tsx
- tests/react/utils/useAtomCallback.test.tsx
- tests/react/utils/useHydrateAtoms.test.tsx
- tests/react/utils/useReducerAtom.test.tsx
- tests/react/utils/useResetAtom.test.tsx
- tests/react/vanilla-utils/atomFamily.test.tsx
- tests/react/vanilla-utils/atomWithDefault.test.tsx
- tests/react/vanilla-utils/atomWithObservable.test.tsx
- tests/react/vanilla-utils/atomWithReducer.test.tsx
- tests/react/vanilla-utils/atomWithRefresh.test.tsx
- tests/react/vanilla-utils/atomWithStorage.test.tsx
- tests/react/vanilla-utils/freezeAtom.test.tsx
- tests/react/vanilla-utils/loadable.test.tsx
- tests/react/vanilla-utils/selectAtom.test.tsx
- tests/react/vanilla-utils/splitAtom.test.tsx
Tests using React Testing Library to should use screen instead of queries returned by `render`.
> test: use screen exposed by React Testing Library

- website/src/components/stackblitz.js
Fixes #2791
- Add ctl=1 as a query parameter to the StackBlitz iframe's src URL.
https://github.com/user-attachments/assets/1b7b78b1-5294-4144-a88a-e6a3faaf78f2
)
https://github.com/user-attachments/assets/1a6dc35b-5d98-4a19-97eb-b3d8481ab2be
)
> fix(website): Add ctl=1 as a query parameter to the StackBlitz iframe's src URL.

- docs/extensions/immer.mdx
Corrected from `useAtom` to `atom`.
> docs: fix typo in Immer

- docs/extensions/location.mdx
Added an important warning note against instantiating `atomWithLocation` more than once in an app
https://github.com/jotaijs/jotai-location/issues/38
> Updated `location.mdx` regarding `atomWithLocation` instances

- src/vanilla/utils/unwrap.ts
- tests/vanilla/utils/unwrap.test.ts
Identical to https://github.com/pmndrs/jotai/pull/2790, but for `unwrap`
This regression is from the change here: https://github.com/pmndrs/jotai/pull/2695
When upgrading from 2.8.4 to 2.10.1, `unwrap` hangs in certain cases. I narrowed it down to atoms such as this one:
`atomWithDefault((get) => get(unwrap(anAsyncAtom)))`
Applying https://github.com/pmndrs/jotai/pull/2790 to `unwrap` fixes things.
Note that the recommended pattern for such atoms is to use two atoms:
```
const atomA = unwrap(anAsyncAtom);
const atomB = atomWithDefault((get) => get(atomA));
```
In this case, inlining `atomA` into `atomWithDefault` only works if `unwrap`'s default fallback is used, meaning the following code will hang:
`const atomB = atomWithDefault((get) => get(unwrap(anAsyncAtom, (prev) => prev ?? …
> fix(utils): make 'unwrap' update immediate after resolve

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
- Adds a test for https://github.com/pmndrs/jotai/pull/2804
- Adds isSync check for setSelf in unmount.
> add test for flushPending

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Errors thrown in flushPending are checked for truthyness. This change allows for falsy errors to be rethrown.
> fix: rethrow falsy errors thrown in flushPending

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
- https://github.com/pmndrs/jotai/discussions/2812
- adds failing test: should use the correct pending on unmount
- fixes failing test
Because setAtom is defined in mountAtom and references that function's pending.
Fix: dependency inject the current pending when invoking the pending functions
> fix: setAtom uses stale pending on atom unmount

- tests/vanilla/dependency.test.tsx
https://github.com/pmndrs/jotai/discussions/2789#discussioncomment-11275111
This PR adds two tests to enforce the behavior:
- _atoms accessed with write get should have their dependencies updated_
> add tests: can read sync derived atom in write without initializing

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
- https://github.com/pmndrs/jotai/discussions/2810
- adds failing test: when changing the atom value with onMount setSelf, subscribers are not called
- fixes failing test
Because the listener is added only after flushPending is called.
Fix: swap the order of flush pending and listeners.add(listener).
Because the listener is deleted before flushPending is called.
There's a logic cycle here:
1. the listener is deleted _before_ calling unmountAtom, because unmountAtom only processes if atomState.m.l.size === 0
2. unmountAtom adds the onUnmount pending function
3. flushPending calls onUnmount pending function
4. setAtom fires in onUnmount pending function, which updates the atom
5. subscriber doesn't fire because it was removed in 1
👉 NOTE: This is expected behavior.
> fix: onMount setSelf does not notify listeners

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Replaces the recursive topo search in recomputeDependents with an iterative one. An iterative approach theoretically is faster and does not suffer from stack overflow issues. This makes it possible to process very large atom graphs.
- Recursive: ~200ms
-  Iterative: ~ 350ms
TODO: Currently the new iterative approach is _slower_ than the recursive one.
> refactor(core): Use iterative approach in recompute dependents

- src/vanilla/store.ts
Replaces value comparisons with epoch number changes. This may help prevent memory leaks.
> refactor(store): prefer epoch number comparisons to indicate value change

- docs/tools/babel.mdx
Just a few changes in the docs page for babel plugins.
> docs: improve babel page

- CONTRIBUTING.md
* Same with https://github.com/pmndrs/zustand/pull/2890
> docs(CONTRIBUTING.md): change 'pnpm' to 'pnpm install' for installing dependencies

- src/vanilla/store.ts
- tests/vanilla/dependency.test.tsx
- tests/vanilla/store.test.tsx
https://github.com/pmndrs/jotai/discussions/2782
Currently, recomputeDependents runs for each call to set. This causes overlapping dependents to recompute multiple times.
We still need to recompute some dependents if they are accessed with `get`. But the remaining dependents can be recomputed at the end of the transaction in flushPending.
```ts
const a = atom(0)
const b = atom((get) => get(a))
const fetch = vi.fn()
const c = atom((get) => fetch(get(a)))
const w = atom(null, (get, set) => {
set(a, 1)
expect(get(b)).toBe(1)
expect(fetch).toHaveBeenCalledTimes(0)
})
const store = createStore()
store.sub(b, () => {})
store.sub(c, () => {})
fetch.mockClear()
store.set(w)
expect(fetch).toHaveBeenCalledOnce()
expect(fetch).toBeCalledWith(1)
expect(store.get(a)).toBe(1)
```
1. on `set`
- keep a …
> lazy recomputeDependents

- src/vanilla/store.ts
- tests/vanilla/dependency.test.tsx
- tests/vanilla/store.test.tsx
The recent refactor #2868 to batching causes a subtle regression in which errors thrown in listeners could cause the remaining listeners for that atom not to run.
This PR flattens listeners to the pending function so errors thown are detected but only rethrown after the remaining listeners have been processed.
> fix(store): robust flush batch

- src/vanilla/store.ts
Centralizes addBatchFunc calls.
> fix(store): refactor batch priority

- src/vanilla/store.ts
~Adds iterable to batch to make flushBatch agnostic to the internals of batch.~
edit: Just refactoring for now delaying the decision
> refactor(core): more readability for addBatchFunc

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Batch.D was previously `Map<Atom, Set<AtomDependent>>`.
This allowed atom dependents to recompute without being mounted. There isn't an obvious reason to do so.
All tests pass after removing this functionality.
After this change, the following test would fail.
I don't think we should be update dependents of unmounted atoms.
```ts
it('recomputes dependents of unmounted atoms', () => {
const a = atom(0)
const bRead = vi.fn((get) => get(a))
const b = atom(bRead)
const c = atom((get) => get(b))
const w = atom(null, (get, set) => {
set(a, 1) // batch.D.set(a, new Set())
get(c) // batch.D.get(a).add(b)
set(a, 2) // topSortedReversed: [b, a]
bRead.mockClear()
// after this write function completes, flushBatch will recompute `a` and `b`
// note: a and b are not mounted
})
const store = …
```
> replace batch dependents map with batched changed atoms

- src/vanilla/store.ts
I wasn't able to notice it in #2912.
> refactor: following up #2912

- rollup.config.mjs
* Same with https://github.com/pmndrs/zustand/pull/2952
* Clarify the callback argument `s` to `str` in `capitalize` function
* Add a `global` comment instead of `eslint-disable`
> chore(rollup): clarify variables, add a 'global' comment

- website/src/pages/index.js
> fix(website): code snippet

- docs/extensions/scope.mdx
The scope of bunshi is not divided based on the provider in the render tree but rather based on the value of the provider, so using `initialCount` as the value of the scope is not appropriate.
If multiple providers provide the same `initialCount`, they will share the same scope.
Therefore, I have modified the example code to wrap the `initialCount` once so that it gets a different reference.
> docs: fix bunshi example

- tests/vanilla/memoryleaks.test.ts
> chore(test): add memory leak tests

- docs/recipes/custom-useatom-hooks.mdx
- docs/recipes/large-objects.mdx
> docs: update selectAtom instructions

- src/vanilla/store.ts
Current implementation with `runWithTransactions` uses a single synchronous callback (`fn`) invocation followed by conditionally running store hooks. For some flows, this code reduces to simply calling `fn`. The states in which hooks should be called are well defined so refactoring to synchronously calling a finalizer (`flushCallbacks`) is introduced in this PR.
A side-effect of this PR is it resolves several incompatibilities with jotai-effect.
`flushCallbacks` is called at the end of 7 flows:
1. writeAtom
2. writeAtomState setter async
3. subscribe
4. unsubscribe
5. readAtomState getter async
6. promise complete
7. onMount setAtom async
> refactor(store): Replace runWithTransactions to flushCallbacks

- src/vanilla/store.ts
- tests/atomEffect/atomEffect.test.tsx
- tests/atomEffect/atomEffect.ts
- tests/atomEffect/test-utils.ts
Uploading atomEffect v1.5 work in progress to finish development. The end goal is all tests pass.
The full implementation is provided towards this goal.
_Not for merge_
```ansi
❯ |jotai| tests/atomEffect/atomEffect.test.tsx (34) 4671ms
✓ should run the effect on vanilla store
✓ should not call effect if immediately unsubscribed
✓ should run the effect on mount and cleanup on unmount once
✓ should run the effect on mount and cleanup on unmount and whenever countAtom changes
✓ should not cause infinite loops when effect updates the watched atom
✓ should not cause infinite loops when effect updates the watched atom asynchronous
× should allow synchronous recursion with set.recurse for first run 1018ms
× should allow synchronous recursion with set.recurse 1003ms
× should allow multiple …
```
> [DO_NOT_MERGE] atom effect (V1.5) development and testing

- docs/extensions/effect.mdx
Update website docs for jotai-effect
- introduces new api `observe`.
> doc: update jotai-effect docs

- docs/extensions/effect.mdx
Improve clarity and conciseness of jotai-effect website docs. Also fixes a few mistakes.
> update jotai-effect docs to improve clarity and conciseness

- docs/utilities/resettable.mdx
Update the import statement in the documentation to correctly show where atomWithRefresh is imported from.
as-is `from 'XXX'`
to-be `from 'jotai/utils'`
> docs: update import statement for atomWithRefresh

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
https://github.com/pmndrs/jotai/discussions/2964
When writeAtomState on activateAction is called, setter is called on isActiveAtom which updates the value to true. isActiveAtom is marked as dirty along with all its dependents; since isActiveAtom is currently mounted, this includes activeCountAtom. Calling getter inside writeAtomState should cause an eager readAtomState on activeCountAtom. Since activeCountAtom is dirty, this should recursively reevaluate all dependencies. In this case, countAtom is conditional and is not yet a dependency of activeCountAtom. So the issue lies with not ~~doing a full readAtomState of activeCountAtom in which its read function is called again~~ calling recomputeDependents prior to calling readAtomState on activeCountAtom. Because the readAtomState was called …
> fix(store): recompute dependents on eager evaluation in writeAtomState

- .github/workflows/test-multiple-builds.yml
- src/vanilla/internals.ts
- src/vanilla/store.ts
- tests/vanilla/effect.test.ts
- fix type typo
- use WeakMap instead of Map for storing callbacks
- export initializeStoreHooks to centralize storeHook callback registration
- createStoreHook for flushHook
> store hooks tweaks

- src/vanilla/internals.ts
- tests/vanilla/derive.test.tsx
~should be merged after #2911.~
Changing my mind, and merging into #2911.
> refactor(internals): isolated mounted map in store

- src/vanilla/internals.ts
- tests/vanilla/effect.test.ts
Return delete function from add in storeHooks.
- improves ergonomics
- reduces bundle size
> storeHooks minor improvement

- .github/workflows/cr.yml
- .github/workflows/lint-and-type.yml
- .github/workflows/livecodes-preview.yml
- .github/workflows/publish.yml
- .github/workflows/test-multiple-builds.yml
- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
- package.json
* Same with https://github.com/pmndrs/zustand/pull/2991
> chore(*): replace 'pnpm <command>' with 'pnpm run <command>'

- .github/workflows/test-multiple-builds.yml
- src/vanilla/internals.ts
- src/vanilla/store.ts
- tests/vanilla/derive.test.tsx
- tests/vanilla/effect.test.ts
- tests/vanilla/store.test.tsx
The reason we had `getAtomState` is for `unstable_derive` and to avoid having state. #2911 goes with a different approach and it has store state. ~We should have atomStateMap there too. Especially, having ensureAtomState function as store state seemed weird.~ Second take is to put everything in store args.
> refactor(internals): store state in store args

- .github/workflows/test-multiple-builds.yml
- package.json
* maintain consistency with Zustand and Valtio.
* Since `test:spec` and `test-build:spec` perform the same operation, i removed the duplicate in `package.json` and replaced it with `test:spec` within the CI.”
> chore(*): remove duplicate 'test-build:spec', replace with 'test:spec'

- .github/workflows/test-multiple-builds.yml
- src/vanilla/internals.ts
- src/vanilla/store.ts
- tests/vanilla/derive.test.tsx
- tests/vanilla/effect.test.ts
- tests/vanilla/store.test.tsx
Expose buildingBlocks by passing in to buildStore.
Background: We sometimes want to use a custom function in place of a building block when creating a new store. This PR is one approach that enables this functionality.
> expose building blocks

- vitest.config.mts
Vitest 3 suggest to migrate from 'basic' reporter to 'default'
```
DEPRECATED  'basic' reporter is deprecated and will be removed in Vitest v3.
Remove 'basic' from 'reporters' option. To match 'basic' reporter 100%, use configuration:
{
"test": {
"reporters": [
[
"default",
{
"summary": false
}
]
]
}
}
```
Secondly, `provider` in `coverage` is required and produces TypeScript error when not defined explicitly.
> chore: use default reporter in vitest and fix TS error

- docs/extensions/query.mdx
I opened the docs for integration of Jotai Query in my React.js project and when I clicked on the links for the reference from original TanStack Query docs, I got to know that TanStack Query have recently updated their docs and Jotai docs are not updated with latest links. So, I found the current links from TanStack Query docs and replaced them with the previous links on Jotai Query docs.
Fixes #
Fixed broken links in the Query extension docs.
Found the working links from Tanstack Query docs and replaced them in Jotai Query extension docs
> docs(query): fix broken links in documentation

- LICENSE
* Regularly updating the copyright year can be unnecessary and tedious.
* Keeping only the initial year makes maintenance easier.
* The MIT license does not require a specific year format.
* Listing just the first publication year is legally sufficient.
* This helps avoid unnecessary updates and keeps the license file clean and simple.
> docs(LICENSE): keep only the initial copyright year

- src/react/Provider.ts
- src/vanilla/store.ts
- src/vanilla/utils/atomFamily.ts
* https://github.com/pmndrs/jotai/pull/3002#pullrequestreview-2640696617
* for exported functions, use function declaration
* for other functions, use const arrow function (and omit return statements if possible.)
> refactor(vanilla, react): change exported functions to 'function declarations' and non-exported ones to 'arrow functions'

- examples/mega-form/src/useAtomSlice.ts
Fixes #
* examples/mega-form remove itemAtom.
I really love Jotai's coding style, but there's a small issue in examples/mega-form that caused me some trouble when getting started with Jotai. I've fixed it.
> fix: examples/mega-form remove itemAtom;

- src/vanilla.ts
- src/vanilla/store.ts
#3023
This allows overriding createStore. It's not very recommended, but can't be helped to avoid breaking changes. We may revisit this in the next major version. cc @arjunvegda
> fix: expose an internal function for devtools

- src/react/useAtomValue.ts
- tests/react/async2.test.tsx
> fix(react): experimental option to make attaching promise status controllable

- docs/recipes/atom-with-listeners.mdx
I might be completely off but on first glance I think it should be `useAtom(countAtom)` instead of `useState(0)`, shouldn't it? 🤔
> docs: fix atom-with-listeners usage example

- src/vanilla/utils/atomWithStorage.ts
Fixes #3054 
This changes the return type of the `subscribe` function to allow undefined. Alternatively, the type of `Unsubscribe` could be changed to `() => void | undefined`, which may be preferable. This doesn't change the functionality of Jotai, and is a type-only issue, so no tests needed to be added or changed, and this simply encompasses the intended existing functionality.
> fix(utils): allow undefined for atomWithStorage subscriber return

- eslint.config.mjs
- vitest.config.mts
Fixes #
* Same with https://github.com/pmndrs/zustand/pull/3116
> chore(eslint): enforce file extension usage for internal modules, ignore external packages

- tests/react/vanilla-utils/freezeAtom.test.tsx
> test(react/vanilla-utils/freezeAtom): add tests for null and primitive handling

- src/react/useAtomValue.ts
- src/vanilla/utils/atomWithObservable.ts
- src/vanilla/utils/atomWithStorage.ts
- src/vanilla/utils/loadable.ts
- src/vanilla/utils/unwrap.ts
Fixes #3065 
Previously, we wrapped all promises in the store code and the use of `instanceof Promise` was safe. However, it's not been true since #2695. This fixes it by using `isPromiseLike` instead.
> fix: support non-native promises

- .github/workflows/test-old-typescript.yml
- src/react/utils/useHydrateAtoms.ts
- tests/react/utils/types.test.tsx
Problem: tests are broken for old typescript versions
Solution: granular SKIP- and ONLY- control for specific ts versions
> fix(tests): fix type testing for useHydrateAtoms for old typescript versions

- package.json
N/A
Upgrade pnpm from v9.15.5 to v10.15.0 to stay up-to-date with latest stable version.
The lockfile format remains compatible (v9.0) so no lockfile changes are needed.
> chore: upgrade pnpm to v10.15.0

- docs/utilities/storage.mdx
Fixes #3134
changed stackblitz project id from
```react
<Stackblitz id="vitejs-vite-wewrmi" file="src%2FApp.tsx" />
```
to a new project id 
```react
<Stackblitz id="vitejs-vite-xvlgfxrk" file="src%2FApp.tsx" />
```
which has added the missing style content.
You can preview at [vitejs-vite-xvlgfxrk](https://stackblitz.com/edit/vitejs-vite-xvlgfxrk?file=src%2FApp.tsx), compared to [old one](https://stackblitz.com/edit/vitejs-vite-wewrmi?file=src%2FApp.tsx).
> fix atomWithStorage stackblitz missing style
