pmndrs/jotai

- .size-snapshot.json
- src/useAtom.ts
`useDebugValue` to see atom value in DEV.
> use debug value

- src/Provider.ts
was it to do that?
all tests passed
😥
> chore: delete item in dependentsMap if is empty

- src/atom.ts
- src/index.ts
- src/types.ts
> export PrimitiveAtom type

- .size-snapshot.json
- src/Provider.ts
- src/atom.ts
- src/types.ts
- src/useAtom.ts
- tests/test.tsx
This is something I gave up as an initial implementation.
This will be annoying soon or later, so I'd put some effort to investigate and possibly fix it. It can be a big change.
~For now, there's only a failing test.~
This is a big change in the end.
> improve atom initialization (lazy read)

- .size-snapshot.json
- src/Provider.ts
- src/useAtom.ts
- tests/items.test.tsx
There's some bugs when we create and delete atoms in React lifecycles.
This fixes with various techniques.
> Fix adding atom and deleting atom

- .size-snapshot.json
- src/useAtom.ts
Follow up https://github.com/react-spring/jotai/pull/33#discussion_r487403633
> fix: do not mutate ref in render

- .size-snapshot.json
- src/Provider.ts
- src/useAtom.ts
- tests/basic.test.tsx
- tests/error.test.tsx
We can't throw from Provider. We need to throw from the hook.
> Implement error propagation

- .size-snapshot.json
- docs/utils.md
- src/utils.ts
> useResetAtom in utils

- src/useAtom.ts
- tests/basic.test.tsx
> type setAtom with never

- .size-snapshot.json
- package.json
- src/Provider.ts
- src/useAtom.ts
- src/useIsoLayoutEffect.ts
- yarn.lock
- `lastState` in Provider should be updated in layout effect. too late with passive effect
- if `isSSR`, invoke the effect in render otherwise effect never fires.
> use iso layout effect

- src/atom.ts
- src/types.ts
- src/utils.ts
This may reduce some confusions.
> Simplify TS typing

- src/atom.ts
- src/types.ts
- src/useAtom.ts
I confused about Promise in types.ts. This should be better.
> fix atom types (NoPromise)

- .size-snapshot.json
- src/types.ts
- src/useAtom.ts
- src/utils.ts
- tests/basic.test.tsx
- tests/error.test.tsx
> support optional action/update

- rollup.config.js
Close #61. Close #63. 
```js
import { useUpdateAtom } from 'jotai/utils.cjs.js'
```
> create csj bundle for utils

- src/Provider.ts
- tests/basic.test.tsx
It was a bit tricky. We need more tests.
> Fix updating dependents

- .size-snapshot.json
- src/Provider.ts
- tests/async.test.tsx
> Fix async stale value

- .size-snapshot.json
- src/Provider.ts
- tests/async.test.tsx
Fix #71 `atom state not found. possibly a bug.` error.
> Fix async atom init

- .size-snapshot.json
- src/Provider.ts
- tests/basic.test.tsx
close #74 
This fixes this certain case, but it's not 100% certain if there's another case failing similarly.
So far, I wasn't able to create another failing test.
> avoid running write before initialization

- .size-snapshot.json
- src/Provider.ts
- tests/async.test.tsx
> Reuse read pending atom state

- package.json
- yarn.lock
> update use-context-selector for rn

- docs/async.md
- docs/core.md
- docs/nextjs.md
- docs/persistence.md
- docs/showcase.md
- docs/typescript.md
- docs/utils.md
- readme.md
Our Tips and QAs in issues are scattered. This simply summarizes them in the docs folder.
Let me close the following issues. I will create another issue for followup.
close #4 
close #15 
close #27 
close #66
> Draft docs

- docs/async.md
- docs/core.md
Fixed two typos in async.md and a grammar mistake in core.md
> Fixed 2 typos and 1 grammar 

- tests/utils/useUpdateAtom.test.tsx
I saw that you needed some tests, so I added this one.
I'm not sure on the format that we want to add tests for utils, I suggest the convention `utils.${function}.test.tsx` or similar, how do you feel about this? Or should we make tests for _all_ functions in one file?
If that's alright, I'll make PR's similar to this one for the remaining functions.
> add tests for useUpdateAtom

- docs/comparison.md
- readme.md
this just move as-is notes into docs.
finally close #13
> add comparison doc

- .size-snapshot.json
- src/core/Provider.ts
- src/core/immutableMap.ts
We plan code refactoring and optimization. This is step 1.
- Introduce new ImmutableMap. This abstracts some logic and hopefully improve readability.
- Simplify readAtom. I think I did something unnecessary...
There some points that we need to investigate further, but I think it's working as is and safe to merge.
> Refactor step 1 with immutable map

- .size-snapshot.json
- src/core/Provider.ts
This will improve write performance. Test are passing, but there could be some edge cases that aren't taken care of.
> Batched writes

- .size-snapshot.json
- package.json
- src/core/Bridge.ts
- src/core/Provider.ts
- tests/basic.test.tsx
- yarn.lock
close #114 
It was a regression when updating use-context-selector v1.2. 😓 
~I wonder if we can write a test for this...~ done (w/ same renderer)
> fix: useBridge with updated use-context-selector

- .size-snapshot.json
- package.json
- rollup.config.js
- src/immer.ts
- src/immer/atomWithImmer.ts
- src/immer/useImmerAtom.ts
- src/immer/withImmer.ts
- yarn.lock
#11 It's ready I think, Feel free to leave comments, suggestions, and ....
> Immer support

- tests/immer/atomWithImmer.test.tsx
- tests/immer/useImmerAtom.test.tsx
- tests/immer/withImmer.test.tsx
#122 @dai-shi, I implemented the tests for immer support, I'll work on the docs in the next PR. I really loved this experience, and again, thanks for the opportunity.
> Immer tests

- .size-snapshot.json
- examples/hacker_news/package.json
- examples/hacker_news/src/App.js
- examples/hacker_news/yarn.lock
@dai-shi 
refer to #86, #121 
I don't know why #121 PR stop updating, so I raise another PR.
> Improve hacker news

- docs/immer.md
#122 @dai-shi I wrote the docs for immer support.
> immer docs

- .size-snapshot.json
- src/core/Provider.ts
- tests/dependency.test.tsx
> Fix updating async atoms with depndencies

- docs/showcase.md
refer to #86 
Update [showcase.md](https://github.com/pmndrs/jotai/blob/master/docs/showcase.md)
* Change `Minimal example` -> `Text Length example`
* Update `codesandbox` link
* Add description for each example
> Improve showcase.md

- examples/text_length/README.md
- examples/todos/README.md
- examples/todos_with_atomFamily/README.md
> Improve rest examples

- package.json
- yarn.lock
> fix: esm build with new use-context-selector

- readme.md
> installation notes for yarn 2

- package.json
- readme.md
- yarn.lock
ref: https://github.com/pmndrs/jotai/issues/135#issuecomment-710782084 https://github.com/pmndrs/jotai/pull/139#discussion_r506916713
> no implicit peer dependency

- .size-snapshot.json
- src/core/Provider.ts
- tests/async.test.tsx
close #147 
There was a big regression in v0.10.0.
We need more async tests.
> fix multiple async atoms initialization

- docs/core.md
This is to close #5 .
reviews/suggestions/improvements are appreciated.
> add a docs/core section about creating atoms on demand

- docs/typescript.md
> docs: add typescript version requirement note

- tests/utils/useSelector.test.tsx
Fixes this: https://github.com/pmndrs/jotai/issues/137
> add useSelector.test

- tests/provider.test.tsx
> test: provider initialValues

- .size-snapshot.json
- package.json
- rollup.config.js
- src/devtools.ts
- src/devtools/useAtomDevtools.ts
Enable [Redux Devtools](https://github.com/reduxjs/redux-devtools) browser extension integration for Jotai.
> Add ReduxDevTools Integration to Jotai

- src/utils/atomFamily.ts
I expect this patch should improve performance when using `atomFamily`
> rewrite atomFamily using Map

- src/utils/atomFamily.ts
> fixes #177: use areEqual in atom remove

- tests/immutableMap.test.ts
closes #107 
Tests the api of immutable map.
> test: immutable map

- tests/utils/useAtomCallback.test.tsx
:tada: I made the tests, Any suggestions, ....
> useAtomCallback tests

- .size-snapshot.json
- src/core/Provider.ts
- tests/async.test.tsx
- tests/dependency.test.tsx
- tests/utils/useSelector.test.tsx
close #184 
This is rather a big refactoring:
- atom revision
- atom dependencies (not dependents)
- dependents map (weak map)
> refactor with atom revision number and dependents weak map

- src/core/useAtom.ts
@dai-shi I was playing with codesandbox, then jotai showed me that error, but I had a provider, then I realized that I didn't put the scope. Maybe helpful for the folks.
> improve useAtom error message

- src/core/Provider.ts
- tests/async.test.tsx
> fix: async dependency behavior

- docs/optics.md
Fixes https://github.com/pmndrs/jotai/issues/209
> fix(docs/optics): fix typo.

- tests/utils/useAtomValue.test.tsx
#212 Tests, any suggestions? @dai-shi
> useAtomValue tests

- tests/utils/useUpdateAtom.test.tsx
@dai-shi  I'm improving the tests as #88 notes and I'll improve other tests soon like basic, dependency,...(I'm a bit busy now)
> improve useUpdateAtom tests

- tests/async.test.tsx
> improve async tests

- .size-snapshot.json
- package.json
- tests/basic.test.tsx
- yarn.lock
https://www.npmjs.com/package/use-context-selector/v/1.3.0
> upgrade use-context-selector

- src/core/Provider.ts
- src/devtools/useAtomDevtools.ts
- src/utils/freezeAtom.ts
> fix webpack 5 process is not defined

- tests/items.test.tsx
> improve items tests

- tests/optics/focus-lens.test.tsx
This discussion lead me to making a test-case that just asserts this behavior:
https://github.com/pmndrs/jotai/issues/231
I think it's good to have a test case so that we don't accidently break something in the future.
> fix(focus-atom): add focus of async atom test

- .size-snapshot.json
- src/core/Provider.ts
- src/core/vanilla.ts
This refactors the core code to improve readability/maintainability and reduce bundle size.
There's a small behavioral change in async atoms, which wouldn't be a problem. Hope someone to file an issue if it causes an unexpected behavior.
> Refactor Provider.ts and vanilla.ts some more

- src/immer/withImmer.ts
- src/optics/focusAtom.ts
- src/utils/freezeAtom.ts
- src/utils/useAtomCallback.ts
- src/utils/useResetAtom.ts
- src/utils/useSelector.ts
- src/utils/useUpdateAtom.ts
- tests/immer/withImmer.test.tsx
- tests/optics/focus-lens.test.tsx
- tests/utils/useResetAtom.test.tsx
- tests/utils/useSelector.test.tsx
- tests/utils/useUpdateAtom.test.tsx
> fix: copy scope when deriving an atom

- package.json
> fix: add package.json explicitly in exports

- .size-snapshot.json
- package.json
- src/core/Provider.ts
- tests/basic.test.tsx
- yarn.lock
> fix: extra commits with changing atoms

- src/immer/atomWithImmer.ts
- src/immer/useImmerAtom.ts
- src/immer/withImmer.ts
- src/optics/focusAtom.ts
- src/utils/atomFamily.ts
- src/utils/useAtomCallback.ts
This is to follow the typing change in #266 and improve some other typings.
> fix: types in immer/optics/utils

- docs/guides/persistence.md
with #266, we can use `onMount` for persistence instead of useEffect.
> fix(docs): update persistence with onMount

- .size-snapshot.json
- package.json
- rollup.config.js
> fix: module build again

- docs/api/core.md
Ref: https://github.com/pmndrs/jotai/discussions/292
> chore: add a note about useBridge

- docs/introduction/showcase.md
adds example for a tic tac toe game implemented using jotai.
> chore: add tic tac toe example using jotai

- src/core/vanilla.ts
- tests/dependency.test.tsx
close #297 
All tests are passing.
I'm not 100% confident with the implementation. There could still be some bugs or unexpected behavior. Also, throwing a promise is still questionable.
> fix: readAtomState in write/get too 

- .size-snapshot.json
- src/core/vanilla.ts
- tests/async.test.tsx
> fix: promise value causing infinite loop

- src/core/vanilla.ts
- tests/async.test.tsx
> fix: async atom chains

- .size-snapshot.json
- docs/api/utils.md
- src/utils/splitAtom.ts
- tests/utils/splitAtom.test.tsx
> fix: splitAtom to support read-only arr atom

- src/core/Provider.ts
- src/core/contexts.ts
- src/core/useAtom.ts
- src/core/vanilla.ts
My [first trial](https://github.com/pmndrs/jotai/tree/feat/atomic-mutable-source) didn't pass some tests. So, this is the second one, which passes all the tests.
(Not 100% certain if we can trust the coverage of our tests.)
> Refactor with useMutableSource scoped subscription

- src/index.ts
- src/utils/useUpdateAtom.ts
obsoletes #331 
I'm more comfortable with this. No breaking changes on public api.
> re-remplement useUpdateAtom with secret internals

- src/core/vanilla.ts
This might not change much for now.
Hope this is better with real uMS and in CM.
At least the code is cleaner. 😁
> refactor with invalidatedRevision

- package.json
> Fix exports 

- package.json
> Re-fix imports

- tests/async.test.tsx
- tests/basic.test.tsx
- tests/dependency.test.tsx
- tests/optimization.test.tsx
- tests/utils/atomFamily.test.tsx
- tests/utils/splitAtom.test.tsx
follow #360 new test file and useCommitCount for others.
> chore: split optimization test, useCommitCount

- docs/introduction/concepts.md
- docs/introduction/getting-started.md
- readme.md
close #319 (focusing on concepts)
> feat(docs): concepts

- docs/guides/no-suspense.md
- readme.md
> [docs] No suspense

- tests/basic.test.tsx
- tests/optimization.test.tsx
in basic.test, checks commits count for write-only atom usage,
in optimization.test, add a new one to check render count (non StrictMode in optimization.test).
> chore: add optimization test spec

- .vscode/launch.json
- src/core/vanilla.ts
- tests/async.test.tsx
> Fix #375 - Atom state is not flushed when using sync invoked async setter

- src/utils/splitAtom.ts
- src/utils/waitForAll.ts
- tests/utils/splitAtom.test.tsx
- tests/utils/waitForAll.test.tsx
> Fix #391 - Scoped splitAtom and waitForAll

- docs/api/utils.md
- src/utils/atomFamily.ts
- tests/utils/atomFamily.test.tsx
> New atom family implementation

- .size-snapshot.json
- src/core/vanilla.ts
ref: https://github.com/pmndrs/jotai/issues/414#issuecomment-817028501
> fix: remove write promise on error too

- docs/introduction/async.md
> feat: async doc

- docs/api/core.md
> fix(docs): provider-less mode

- docs/api/zustand.md
- package.json
- src/zustand.ts
- src/zustand/atomWithStore.ts
- tests/zustand/atomWithStore.test.tsx
- yarn.lock
following #405, but the implementation is much simpler as both zustand and jotai are based on immutable state.
> Is this worth adding?
Implementation-wise, it's simple. But, it would be worth to show the pattern explicitly.
It would be nice to elaborate docs to show real use cases.
> feat: jotai/zustand

- src/optics/focusAtom.ts
from: https://github.com/pmndrs/jotai/issues/231#issuecomment-820163116
focusAtom can be improved to require not `PrimitiveAtom<T>` but just symmetric `WritableAtom<T, T>`.
> fix: generalize typing in focusAtom

- docs/guides/persistence.md
> fix(docs): improve persistence

- src/redux/atomWithStore.ts
- src/valtio/atomWithProxy.ts
- src/zustand/atomWithStore.ts
- tests/redux/atomWithStore.test.tsx
- tests/valtio/atomWithProxy.test.tsx
- tests/zustand/atomWithStore.test.tsx
following up: #405, #419, #421
It should sync the atom value on mount.
> fix(valtio,zustand,redux): run callback once on mount

- .size-snapshot.json
- src/core/types.ts
- src/core/useAtom.ts
- src/core/vanilla.ts
- src/utils/useAtomValue.ts
- tests/async.test.tsx
fix #434 
fix #430 
- rewrite atomWithQuery (a follow-up PR)
> feat(core): interruptable promise

- src/core/types.ts
- src/core/useAtom.ts
- src/core/vanilla.ts
- src/xstate/atomWithMachine.ts
- tests/async.test.tsx
- fix #442 
- improve async typing with overloads
> fix(core): async atom infinite loop bug

- .size-snapshot.json
- src/devtools/useAtomDevtools.ts
> feat: allow import of json to devtools

- src/utils/atomWithStorage.ts
> fix: atomWithStorage set value in sync if not promise

- .size-snapshot.json
- src/core/Provider.ts
- src/core/contexts.ts
- src/core/vanilla.ts
- src/devtools/useAtomsSnapshot.ts
- tests/onmount.test.tsx
- fix onmount test -> follow-up pr
- fix quey/atomWithQuery test -> follow-up pr
> fix: debug store

- src/utils/useAtomCallback.ts
> Fix typing for `useAtomCallback` returning a Promise.

- .size-snapshot.json
- src/core/vanilla.ts
- tests/dependency.test.tsx
> fix: remount atoms with dependencies

- .size-snapshot.json
- src/core/vanilla.ts
- tests/dependency.test.tsx
While I was looking into an issue discussed in #500, I found a bug.
This fixes it. It turns out that it's not directly related to #500.
> fix: remount atoms with intermediates

- src/immer/atomWithImmer.ts
- src/immer/withImmer.ts
- tests/immer/atomWithImmer.test.tsx
- tests/immer/withImmer.test.tsx
> Add WritableAtom<Value, Value> support in immer integration

- src/core/vanilla.ts
- tests/async.test.tsx
I happen to notice a failing test and fixed it. I feel like there can be a better fix, though...
> fix(core): write atom promise value

- .size-snapshot.json
- src/core/vanilla.ts
> fix: flush pending undefined error

- .size-snapshot.json
- src/devtools/useAtomDevtools.ts
`const action` is never used and removing that make `const actions` useless.
> refactor(devtools): remove unused code

- .size-snapshot.json
- src/core/atom.ts
- src/core/typeUtils.ts
- src/core/vanilla.ts
- src/index.ts
- src/utils/freezeAtom.ts
- src/utils/useAtomCallback.ts
close #522.
This is still an experimental/undocumented feature. We would like to collect some feedback and wait for suspense era to arrive.
> fix(core): add experimental promise option for write getter

- .size-snapshot.json
- src/utils.ts
- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
> fix(utils/atomWithStorage): async storage support

- .size-snapshot.json
- src/core/vanilla.ts
> chore(core): write getter default parameter instead of optional parameter

- examples/hacker_news/src/App.tsx
Modify content:
1. Supplement the type definition of `PostData`
2. Add a condition whether to show `url` or not
> fix: improved template for Hacker News

- src/utils/atomWithObservable.ts
> fix(utils): patch symbol type in atomWithObservable

- src/utils/useAtomCallback.ts
> fix(utils): improve useAtomCallback performance

- .eslintrc.json
- src/core/useAtom.ts
- tests/items.test.tsx
- tests/types.test.tsx
- tests/urql/atomWithQuery.test.tsx
- tests/urql/atomWithSubscription.test.tsx
- tests/valtio/atomWithProxy.test.tsx
I've been wondering why some of rules didn't seem to work, but none of custom rules weren't working.
> chore: eslint rules were broken

- .size-snapshot.json
- src/urql/atomWithQuery.ts
- src/urql/atomWithSubscription.ts
- tests/urql/atomWithQuery.test.tsx
- tests/urql/atomWithSubscription.test.tsx
close #649 
I actually like this new implementation with function overloads.
> fix(urql): support pause option

- src/urql/atomWithQuery.ts
- tests/urql/atomWithQuery.test.tsx
> feat(urql): support reexecute in atomWithQuery

- src/immer/withImmer.ts
- src/optics/focusAtom.ts
- src/utils/freezeAtom.ts
- src/utils/loadable.ts
- src/utils/selectAtom.ts
- src/utils/splitAtom.ts
- src/utils/waitForAll.ts
- src/utils/weakCache.ts
putting typical pattern in a function. better typing.
> refactor: with memoizeAtom

- src/core/store.ts
While I was doing another refactoring, I got this idea. This should be cleaner.
The equality check is for edge cases or maybe hypothetical. We don't have any tests to reveal it.
(If someone is interested in core, it'd be a good and tough challenge.)
> refactor(core): interruptable promise implementation

- src/core/store.ts
- tests/error.test.tsx
- tests/utils/atomWithObservable.test.tsx
Resolves conflicts for #636. Tests for #622.
> add test for urql client null #636 

- src/utils/loadable.ts
- src/utils/selectAtom.ts
- src/utils/splitAtom.ts
From: https://github.com/pmndrs/jotai/pull/730#discussion_r716109779
cc @Pinpickle
> refactor(utils): loadable util

- tests/async.test.tsx
This adds a failing test to help resolve #742.
> test: add test for #742

- tests/error.test.tsx
> refactor(tests): checking console error messages, following up #740

- tests/error.test.tsx
- tests/utils/selectAtom.test.tsx
- tests/utils/useHydrateAtoms.test.tsx
- tests/utils/useUpdateAtom.test.tsx
> refactor(tests): no FC, useEffect for commitCount

- tests/valtio/atomWithProxy.test.tsx
to be consistent with other tests.
> fix(test): improve valtio test

- tests/async.test.tsx
> chore(tests): remove no longer necessary Suspense

- src/core/store.ts
follow up #766. Currently, I don't have an idea to write tests to detect this, but logic-wise, this should be it.
> fix(core): interruptable promise handling

- .eslintrc.json
- src/core/store.ts
- src/devtools/useAtomDevtools.ts
- src/optics/focusAtom.ts
- src/utils/atomFamily.ts
- src/utils/splitAtom.ts
- src/utils/weakCache.ts
- tests/query/fakeFetch.ts
- tests/urql/atomWithMutation.test.tsx
- tests/urql/atomWithQuery.test.tsx
following https://github.com/pmndrs/zustand/pull/678
> chore(eslint): add recommended rules and etc

- tests/query/atomWithQuery.test.tsx
copying one of tests in jotai/urql.
> fix(test): add dependency test in jotai/query

- .swcrc
Fixes line reporting when tests are failing.
> Fix Jest line reporting

- src/core/store.ts
- src/core/suspensePromise.ts
This includes various refactors.
- interruptable promise -> suspense promise
- eliminate prepareNextAtomState
- simplify setting promise on write (this changes the behavior slightly)
> fix(core): refactor store with suspense promise

- src/core/store.ts
Another refactor I wanted to do.
> fix(core): refactor store readAtomState

- src/core/store.ts
- tests/dependency.test.tsx
This is a small refactor, but also changes a subtle behavior which is introduced in #866.
> fix(core): refactor store (setAtomPromiseOrValue)

- docs/api/utils.mdx
- docs/utils/atom-family.mdx
- docs/utils/atom-with-default.mdx
- docs/utils/atom-with-hash.mdx
- docs/utils/atom-with-observable.mdx
- docs/utils/atom-with-reducer.mdx
- docs/utils/atom-with-reset.mdx
- docs/utils/atom-with-storage.mdx
- docs/utils/freeze-atom-creator.mdx
- docs/utils/freeze-atom.mdx
- docs/utils/reset.mdx
- docs/utils/select-atom.mdx
- docs/utils/split-atom.mdx
- docs/utils/use-atom-callback.mdx
- docs/utils/use-atom-value.mdx
- docs/utils/use-hydrate-atoms.mdx
- docs/utils/use-reducer-atom.mdx
- docs/utils/use-reset-atom.mdx
- docs/utils/use-update-atom.mdx
- docs/utils/wait-for-all.mdx
> docs: Split utils into separate doc pages

- src/utils/atomWithStorage.ts
https://github.com/pmndrs/jotai/issues/882#issuecomment-990384275
> (ah, I found a bug in `createJSONStorage`... `setItem` doesn't return a promise on async.)
This is to address it.
> fix(utils): atomWithStorage with async json storage

- src/core/store.ts
- src/core/useAtom.ts
- document the meaning of store production methods
- document reasoning in useAtom
Please review for correctness of these comments!
> Comment store and useAtom internals

- docs/guides/composing-atoms.mdx
> docs(guides): Composing atoms

- package.json
This improves developer experience for eg iterating on devtools.
> Add "yarn watch" script to package.json

- docs/api/utils.mdx
- docs/utils/atom-with-hash.mdx
- docs/utils/atom-with-storage.mdx
- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
> fix(utils): support RESET for atomWithStorage and atomWithHash

- rollup.config.js
Follow the thread: https://github.com/pmndrs/zustand/pull/740
Hi @dai-shi , I did the same config here.
> fix(build): Generate umd and system files

- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
close #949
This was caused by my addition of deprecation warning in #934.
> fix(utils): atomWithStorage should deal with no localStorage

- docs/integrations/immer.mdx
> docs(integrations): atomWithImmer: countAtom var

- docs/utils/freeze-atom.mdx
refer to #963 
`freezeAtom` docs is unclear, and needs some improvements, on both explanations and examples. This PR is for explanation improvement, I'll open another PR for the example.
> Improve freezeAtom documentation

- src/core/store.ts
- tests/async.test.tsx
While I was working on #854, I kind of knew isSync in writeStateAtom was somewhat incomplete. But, I didn't make it work then to make tests pass. While working on #960 lately, I think I'm able to fix it. (But that doesn't fix #947 unfortunately.)
> fix(core): handle some edge cases with flushPending loop

- src/devtools/useAtomsDevtools.ts
https://github.com/pmndrs/jotai/issues/965#issuecomment-1014280761
> chore(devtools): correct error message in useAtomsDevtools

- docs/guides/composing-atoms.mdx
> docs(guides): fix typo

- docs/guides/core-internals.mdx
Created a simplified core implementation doc from Daishi's tweets. Added comments and some description for easy understanding.
> docs: Add simplied core internals implementation

- docs/advanced-recipes/custom-useatom-hooks.mdx
Add some annotations and update `focusAtom` & `selectAtom` utility function with `useCallBack.
> [docs] Update custom hooks for better understanding

- docs/guides/typescript.mdx
> fix(docs): add a note about typescript config

- docs/guides/core-internals.mdx
I made a few minor language changes, with the hope that it improves the readability and tone.
> Some minor language changes

- src/utils/atomWithStorage.ts
- tests/utils/atomWithStorage.test.tsx
> fix(utils/atomWithStorage): handle edge case of value inconsistency with subscription

- docs/utils/wait-for-all.mdx
> chore(docs): waitForAll with objects

- tests/async.test.tsx
- tests/query/atomWithQuery.test.tsx
- tests/utils/atomWithObservable.test.tsx
- tests/utils/waitForAll.test.tsx
to make CI stable. this is just unfortunate. (anyone has deep experience with fake timer?)
> chore(tests): tweak timing

- docs/utils/split-atom.mdx
- src/utils/splitAtom.ts
- tests/utils/splitAtom.test.tsx
> feat(utils): splitAtom actions for remove/insert/move

- src/core/atom.ts
- src/core/store.ts
- src/core/useAtom.ts
- src/core/useAtomValue.ts
- src/utils/loadable.ts
- src/utils/selectAtom.ts
- src/utils/waitForAll.ts
- tests/utils/waitForAll.test.tsx
we define own `Awaited` as downlevel-dts doesn't support it.
> fix(core,utils): improve awaited types and waitForAll type

- src/utils/useAtomCallback.ts
- tests/utils/useAtomCallback.test.tsx
> fix(utils): make useAtomCallback return sync if possible

- .github/workflows/test-multiple-builds.yml
- .swcrc
- src/utils/atomWithObservable.ts
- tests/utils/atomWithObservable.test.tsx
> fix(utils): atomWithObservable: fix ReferenceError with BehaviourSubject (#1156)

- src/core/store.ts
- tests/optimization.test.tsx
Fix https://github.com/pmndrs/jotai/issues/1158#issuecomment-1126839533
> fix(core): do not re-render if value is the same

- src/urql/atomWithQuery.ts
- tests/urql/atomWithQuery.test.tsx
While working on #1154, I noticed an improvement for atomWithQuery. For fixing tests, it was probably due to my lack of knowledge back then.
> refactor(urql): atomWithQuery with fixing tests

- docs/api/utils.mdx
- docs/basics/primitives.mdx
- docs/guides/async.mdx
- docs/guides/composing-atoms.mdx
- docs/guides/core-internals.mdx
- docs/guides/debugging.mdx
- docs/guides/persistence.mdx
- docs/guides/react-native.mdx
This is the follow-up of [this PR](https://github.com/pmndrs/jotai/pull/1083) that I believe is way too old compared to the importance.
Wanted to prevent it from staling ;) 
EDIT: Maybe it's not the best place @sandren ? I know u've been working on Introduction recently. Maybe you know better where to put this or even if it's still needed. Very good job by the way, the Table of contents is great!
> docs(primitives): clarify what can contain an atom

- docs/guides/persistence.mdx
Fixing [unfinished issue](https://github.com/pmndrs/jotai/issues/805) with missing sessionStorage instructions
> docs(persistence): add sessionStorage

- src/core/store.ts
- tests/optimization.test.tsx
> fix(core): avoid extra re-renders after commit with derived atoms

- tests/dependency.test.tsx
> test(core): add test for #1250

- docs/integrations/xstate.mdx
- tests/xstate/atomWithMachine.test.tsx
> Docs and examples for restartable machine atom

- src/core/store.ts
- tests/utils/loadable.test.tsx
> fix(core): resolve infinite loop issue in loadable util with error propagation

- docs/guides/async.mdx
avoid using useEffect, which might not be best practice.
> fix(docs): async guide

- docs/advanced-recipes/atom-creators.mdx
Docs for new `atomWithDebounce` atom creator as discussed here: https://github.com/pmndrs/jotai/discussions/553#discussioncomment-3354600
> docs: atomWithDebounce atomCreator

- src/devtools/useAtomsSnapshot.ts
Task: invalidating atoms in #911 
Tries to ignore the snapshots of invalidated atoms, as inspired by useAtomsDevtools!
> feat: Ignore invalidated atoms in useAtomsSnapshot

- docs/guides/typescript.mdx
added a missing closing parenthesis
> fix(docs): add missing parenthesis

- package.json
- src/urql/atomWithQuery.ts
- src/urql/atomWithSubscription.ts
- yarn.lock
and include small type fixes in jotai/urql.
close #1384.
> chore(deps): update typescript 4.8

- src/core/store.ts
- tests/utils/loadable.test.tsx
close #1392
in a very hacky way. we should revisit this.
> fix(core,utils): loadable with StrictMode

- examples/hacker_news/src/App.tsx
> fix(examples): fix types in hacker_news

- src/core/typeUtils.ts
- src/core/useAtom.ts
- src/core/useAtomValue.ts
- src/core/useSetAtom.ts
- src/index.ts
> fix(types): overload useAtom* type for union atom type

- src/core/store.ts
- tests/utils/atomWithObservable.test.tsx
while working on #1473, I found a possible bug in an edge case.
> fix(core): make atomWithObservable to work with versionedWrite

- docs/api/swc.mdx
- docs/guides/debugging.mdx
- docs/guides/nextjs.mdx
- docs/introduction.mdx
- readme.md
> docs(swc): Add docs for SWC plugins

- tests/core/async.test.tsx
- tests/utils/abortableAtom.test.tsx
- tests/utils/atomFamily.test.tsx
- tests/utils/atomWithDefault.test.tsx
- tests/utils/atomWithObservable.test.tsx
- tests/utils/atomWithStorage.test.tsx
- tests/utils/loadable.test.tsx
- tests/utils/waitForAll.test.tsx
and another fix to replace https://github.com/pmndrs/jotai/pull/1527/commits/7f169c8eb0c6ea1ca48e4283decb06e5f0790c68 which is not stable
> chore(tests): improve tests/utils

- docs/integrations/query.mdx
Fixes #1105 
Docs for `react-query-devtools`
> docs(query): add docs for react-query-devtools

- tests/core/async.test.tsx
- tests/urql/atomWithQuery.test.tsx
- tests/utils/abortableAtom.test.tsx
- tests/utils/atomWithDefault.test.tsx
> chore(tests): make tests more stable

- docs/integrations/urql.mdx
fix https://github.com/jotai-labs/jotai-urql/issues/3
> fix(docs): jotai-urql examples

- src/core/store.ts
my first PR from github codespaces.
> refactor(types): simplify with AnyWritableAtom

- docs/integrations/zustand.mdx
> refactor(docs): fix spelling

- docs/integrations/molecules.mdx
[jotai-molecules](https://github.com/saasquatch/jotai-molecules) is a nice wrapper library for more complex use cases.
> docs: add molecules integration

- src/vanilla/atom.ts
- src/vanilla/store.ts
- src/vanilla/utils/atomWithDefault.ts
- src/vanilla/utils/loadable.ts
- src/vanilla/utils/unwrapAtom.ts
- tests/react/async2.test.tsx
- tests/vanilla/types.test.tsx
> feat(vanilla): refactor v2 API with setSelf removing retry

- src/vanilla/store.ts
follow up #1611.
I forgot something is no longer used, so removed.
> refactor(vanilla): simplify store impl (v2 API)

- src/vanilla/utils/unwrap.ts
- tests/vanilla/utils/unwrap.test.tsx
`fallback` function instead of `default` value for more flexibility.
> fix(vanilla/utils): re-implement unwrap util (v2 API)

- src/vanilla/utils/splitAtom.ts
> refactor(vanilla/utils): avoid refAtom in splitAtom (v2 API)

- tests/react/async2.test.tsx
to cover the use case like https://twitter.com/dai_shi/status/1604306676026290176
> chore(tests): add an async test for the new behavior in v2

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
> fix(vanilla): do not invoke callback on subscribe (v2 API)

- tests/react/vanilla-utils/atomWithObservable.test.tsx
- tests/utils/atomWithObservable.test.tsx
#1498 will still take time, so here's a workaround temporarily.
> fix(tests): avoid using fake timers for now

- tests/react/vanilla-utils/atomWithObservable.test.tsx
- tests/utils/atomWithObservable.test.tsx
follow up #1676
...should help a little bit.
> fix(tests): change fake timeout

- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
- package.json
- tests/core/transition.test.tsx
- tests/react/abortable.test.tsx
- tests/react/transition.test.tsx
- tests/setVersionedWriteMode.ts
in CI. And, drop some tests towards v2. related: #1671
> Update react experimental builds

- benchmarks/simple-read.ts
- benchmarks/simple-write.ts
- benchmarks/subscribe-write.ts
> chore(benchmark): fix tool for v2

- docs/guides/nextjs.mdx
Discussion #1709.
Update the description of Provider usage in SSR scenario to make it a bit more clear.
> Docs: SSR Provider Usage

- website/src/pages/index.js
we'll revisit if we can provide a better example.
> fix(website): make the SSR usage minimal

- website/src/pages/index.js
Fixes typos on website main page. (`animeAtom`)
> fix(website): fix typos on animeAtom

- package.json
- website/gatsby-browser.js
- website/gatsby-config.js
- website/gatsby-shared.js
- website/gatsby-ssr.js
- website/package.json
- website/src/atoms/index.js
- website/src/components/external-link.js
- website/src/components/layout.js
- website/src/components/logo-cloud.js
- website/src/components/toggle.js
- website/src/pages/index.js
- website/src/styles/layout.css
- website/yarn.lock
The PR does the following:
- adds new logo cloud to the home page
- updates the website to use Jotai v2, including the new store and provider API
- recommends that Gatsby users disable `DEV_SSR` to enjoy React Fast Refresh support
> feat(website): add logo cloud

- docs/api/core.mdx
- website/gatsby-config.js
- website/src/components/mdx.js
- website/src/pages/index.js
This PR should improve the search results for keywords such as 'store' and 'provider'.
> feat(website): add keywords to search index

- package.json
following https://github.com/pmndrs/valtio/pull/649
> fix(build): improve patch scripts

- docs/guides/testing.mdx
- docs/integrations/relay.mdx
- docs/utilities/ssr.mdx
ref: https://github.com/pmndrs/jotai/discussions/1514#discussioncomment-4863616
Forgot to fix some docs.
> fix(docs): replacing initialValues prop

- tests/react/vanilla-utils/atomWithObservable.test.tsx
> chore(tests): tweak timeout value for slower cpu

- docs/utilities/select.mdx
- src/vanilla/utils/selectAtom.ts
ref: https://github.com/pmndrs/jotai/discussions/1304#discussioncomment-4857393
> fix(vanilla/utils): improve selectAtom for more use cases

- docs/guides/migrating-to-v2-api.mdx
> chore(docs): add note about tree shaking

- package.json
- tests/react/abortable.test.tsx
- tests/react/transition.test.tsx
- yarn.lock
- Improve tests for abortable atom
> tests: improve test reliability

- src/vanilla/utils/atomWithDefault.ts
Fixes #1769 
Overload function to improve DX. Precisely the typing isn't 100% accurate.
> fix(utils): tweak atomWithDefault types for better DX

- docs/guides/debugging.mdx
> docs: fix broken links

- docs/core/atom.mdx
- docs/guides/migrating-to-v2-api.mdx
https://github.com/pmndrs/jotai/discussions/1782#discussioncomment-5055161
Add note section in api section and add a link from v2 migration guide.
> fix(docs): add note about infinite loop

- docs/guides/migrating-to-v2-api.mdx
Fixes #1791
Note it's breaking, and add a link to a discussion.
> fix(docs): add a note about breaking change in atomWithStorage

- docs/core/store.mdx
ref: https://twitter.com/xudading/status/1630388058741719043
> fix(docs): add store unsub example

- docs/guides/migrating-to-v2-api.mdx
Fixes #1791 #1803
See if the documentation makes it more clear
> fix(docs): clarify on atomWithStorage in v2

- src/vanilla/utils/loadable.ts
closes https://github.com/pmndrs/jotai/pull/1794
- Export Loadable type
> fix(utils, types): added export of Loadable type

- CONTRIBUTING.md
- Add/Amend Core lib + Docs contribution guides
- Update commit types sections to include the supported commit types (prepares us for auto-changelog generation in the future)
- Update the pull request section to ask contributors to enable edits from maintainers
> docs(CONTRIBUTING.md): improve contribution guide

- docs/basics/comparison.mdx
Noticed a hard to read part, I propose these changes.
> fix(docs): reword comparison

- readme.md
> fix(docs): Minor changes in readme.md file

- website/src/components/tabs.js
This PR improves the contrast of the tabs for a better UX on the dark mode home page.
> feat(website): improve dark mode

- docs/tools/devtools.mdx
- Relevant PR https://github.com/jotaijs/jotai-devtools/pull/42
- Ready to be merged at any time
> docs(DevTools): add note about @emotion/react + misc. updates

- tests/react/vanilla-utils/atomWithObservable.test.tsx
Fixes https://github.com/pmndrs/jotai/issues/1498
- Use [18.3.0-next-1308e49a6-20230330](https://www.npmjs.com/package/react/v/18.3.0-next-1308e49a6-20230330) to resolve the fake timer issue
> fix(tests): fix react test with fake timers

- .github/workflows/test-old-typescript.yml
> fix workflow file for old ts

- docs/guides/performance.mdx
`performance.mdx` code typo fix
> performance.mdx code typo fix

- docs/guides/typescript.mdx
Add additional explanation of how to correctly type derived atoms.
#1870
> Improve typescript documentation

- docs/guides/persistence.mdx
- docs/utilities/family.mdx
Related PR https://github.com/pmndrs/jotai/pull/1903#issuecomment-1528991568
Updated the  Family and Persistence example to v2
- Persistence sandbox: https://codesandbox.io/s/jotai-todos-g96xjx
- Persistence with `atomFamily` sandbox: https://codesandbox.io/s/jotai-persistence-with-atomfamily-oyiw5r
- Family sandbox: https://codesandbox.io/s/jotai-atomfamily-huxd4i
> docs: update Family and Persistence examples to v2

- docs/integrations/urql.mdx
https://github.com/jotaijs/jotai-urql/pull/12
Update urql documentation to align with current version
- [] `yarn run prettier` for formatting code and docs
> fix(docs): Update urql.mdx

- docs/utilities/ssr.mdx
- src/react/utils/useHydrateAtoms.ts
> docs(react): iterator type on es5 target (#1900)

- CONTRIBUTING.md
> docs: fix typo in CONTRIBUTING.md 

- docs/utilities/family.mdx
Requested here: https://github.com/pmndrs/jotai/discussions/1949#discussioncomment-5963565
Without `set()` the updates aren't committed.
> fix(docs): atomFamily example missing set() usage

- docs/tools/devtools.mdx
Related: https://github.com/jotaijs/jotai-devtools/pull/79
- Document new time travel-related options
> docs: add new time travel props

- src/vanilla/utils/selectAtom.ts
- tests/vanilla/utils/types.test.tsx
> fix(utils): improve selectAtom typing

- src/vanilla/utils/unwrap.ts
- tests/vanilla/utils/types.test.tsx
- tests/vanilla/utils/unwrap.test.ts
just pass through the write functioin.
> fix(utils): unstable_unwrap to support writable atom

- src/vanilla/utils/loadable.ts
- tests/react/vanilla-utils/loadable.test.tsx
Fixes #1843
It catches sync errors and set `hasError`.
> fix(utils): loadable handles sync errors

- src/vanilla/store.ts
Fixes #2044
Add a DEV-only warning message if duplication is detected.
> fix(vanilla): check duplicated instances

- website/src/components/docs.js
- website/yarn.lock
This PR adds all docs to the sidebar.
> feat(website): add all docs to sidebar

- src/vanilla/store.ts
Refer https://github.com/pmndrs/jotai/pull/2061#discussion_r1286497058
> fix: global number of instances flag

- .github/workflows/test-old-typescript.yml
> test with more ts versions in CI

- tests/react/vanilla-utils/atomWithObservable.test.tsx
it's a bit verbose when debugging :)
> chore(tests/utils): suppress error boundary error log

- website/package.json
- website/src/components/toc.js
- website/yarn.lock
This PR improves the table of contents for the recipes section (closes https://github.com/pmndrs/jotai/discussions/2109).
> feat(website): improve table of contents

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
> fix(vanilla): should update derived atoms during write

- website/src/pages/index.js
None
[pnpm install](https://pnpm.io/cli/install) is meant to install all the dependencies in the project (I believe it also works to add new dependencies just for compatibility with `npm`, but that's not the recommended way to add a dependency using pnpm).
[pnpm add](https://pnpm.io/cli/add) is what we need to add a dependency to the project.
> docs: use correct pnpm command

- docs/guides/initialize-atom-on-render.mdx
- docs/integrations/scope.mdx
It includes both:
- [jotai-scope](https://github.com/jotaijs/jotai-scope)
- [bunshi](https://github.com/saasquatch/bunshi) (formerly `jotai-molecules`)
Close https://github.com/jotaijs/jotai-scope/issues/3
> feat(docs): scope integration

- docs/integrations/scope.mdx
> doc: remove duplicate imports from jotai-scope documentation

- src/vanilla/store.ts
Does this improve bundle size?
> refactor(vanilla): simplify conditions

- docs/integrations/scope.mdx
https://github.com/jotaijs/jotai-scope/pull/5
The API is slightly changed, and the example is updated.
> fix(docs): follow jotai-scope v0.3.0

- docs/integrations/scope.mdx
https://github.com/jotaijs/jotai-scope/pull/9
Update the codesandbox link.
> fix(docs): update jotai-scope v0.4.0 usage

- package.json
Publint warnings -> https://publint.dev/jotai@2.5.0
Apply publint recommendations
> Apply publint recommendations

- docs/guides/async.mdx
> docs: fix typo

- .github/workflows/test-old-typescript.yml
> ci: add typescript 5.3.2

- readme.md
> docs: update suspense badge

- src/vanilla/utils/constants.ts
This improves debugging as the symbol no longer appears anonymous in logs.
https://github.com/pmndrs/jotai/discussions/2306
Fixes #
> fix(utils): add description for the RESET symbol.

- benchmarks/simple-read.ts
- benchmarks/simple-write.ts
- benchmarks/subscribe-write.ts
- tsconfig.json
fix https://github.com/pmndrs/jotai/pull/1687#issuecomment-1872456507
> fix: benchmarks

- benchmarks/simple-read.ts
- benchmarks/simple-write.ts
- benchmarks/subscribe-write.ts
Fixes #
I think it might be better to put all the results together.
> chore: benchmarks

- docs/utilities/storage.mdx
- src/vanilla/utils.ts
- src/vanilla/utils/atomWithStorage.ts
Fixes #1198
Add `withStorageValidator` util.
> feat(utils): add withStorageValidator

- docs/guides/persistence.mdx
https://github.com/pmndrs/jotai/discussions/1627#discussioncomment-8127231
Remove an obsolete description about Jotai v1.
> chore(docs): remove obsolete section in persistence guide

- website/src/pages/index.js
N/A
Just fixed a tiny grammar error I spotted :)
N/A
> fix(website/home): Configuration section copyedit

- src/vanilla/utils/atomWithReducer.ts
for https://github.com/jotaijs/jotai-scope/issues/16
This is something I missed in #2186.
> fix(utils): atomWithReducer for jotai-scope

- .github/workflows/livecodes-post-comment.yml
- .github/workflows/livecodes-preview.yml
- .livecodes/react.json
based on:
- https://github.com/live-codes/preview-in-livecodes
- https://github.com/hatemhosny/preview-in-livecodes-demo
> add livecodes preview workflow

- .github/workflows/livecodes-post-comment.yml
- .github/workflows/livecodes-preview.yml
- .livecodes/react.json
> fix livecodes workflow

- .livecodes/react.json
> fix livecodes template

- src/vanilla/utils/atomWithStorage.ts
- tests/react/vanilla-utils/atomWithStorage.test.tsx
> fix(types): fix withStorageValidator type

- tests/react/async.test.tsx
- vitest.config.ts
> chore(tests): suppress logs

- src/vanilla/utils/atomWithStorage.ts
- tests/react/vanilla-utils/atomWithStorage.test.tsx
> fix(types): withStorageValidator

- docs/extensions/trpc.mdx
> docs: add refreshing functionality to tRPC code example

- src/vanilla/store.ts
https://github.com/pmndrs/jotai/discussions/2460#discussioncomment-8858974
> fix(vanilla): improve dual instance warning in DEV

- docs/extensions/effect.mdx
- docs/guides/migrating-to-v2-api.mdx
- docs/utilities/storage.mdx
> docs: fix some typos

- docs/guides/debugging.mdx
- src/vanilla/utils/freezeAtom.ts
- tests/react/vanilla-utils/freezeAtom.test.tsx
Let's just use the improved `freezeAtom`.
> deprecate freezeAtomCreator

- src/vanilla/utils/freezeAtom.ts
> fix(utils): dev-only deprecation message

- .github/workflows/test-multiple-builds.yml
- package.json
We are introducing store2 only tests: #2533, #2534
> fix(ci): test build only for store1

- src/vanilla/store.ts
- tests/react/dependency.test.tsx
Fixes #2554
It seems a regression with #2396.
> fix(store): properly update atom values with edge-case dependency

- tests/react/vanilla-utils/atomWithObservable.test.tsx
React changed some behaviors with error logging.
> chore(tests): suppress error log

- .github/workflows/test-old-typescript.yml
- package.json
- pnpm-lock.yaml
> chore: bump typescript

- src/vanilla/store.ts
> refactor(core): follow naming convention

- .github/workflows/compressed-size-action.yml
- src/vanilla/store.ts
another refactor split from #2652.
> refactor(core): store with Object.assign

- .github/workflows/test-old-typescript.yml
- src/babel/plugin-debug-label.ts
- src/babel/plugin-react-refresh.ts
- src/babel/preset.ts
- src/vanilla/utils/atomWithLazy.ts
- tsconfig.json
following https://github.com/dai-shi/waku/pull/214
> chore: enable verbatimModuleSyntax in tsconfig

- tests/vanilla/dependency.test.tsx
> chore(tests): make sure deps are cleared on each read call

- examples/hello/src/style.css
- Removed the duplicate  'width' property in the CSS files.
> style: removed duplicate width property in CSS files

- docs/utilities/family.mdx
Fixes #
Just a typo fix in docs
> docs: update family.mdx grammar

- .eslintrc.json
- package.json
- pnpm-lock.yaml
- tests/react/async.test.tsx
- tests/react/onmount.test.tsx
- tests/react/optimization.test.tsx
- tests/react/transition.test.tsx
- tests/react/vanilla-utils/atomWithObservable.test.tsx
- tests/react/vanilla-utils/splitAtom.test.tsx
- tests/vanilla/store.test.tsx
Testing Library provides [Eslint plugin ](https://testing-library.com/docs/ecosystem-eslint-plugin-testing-library) which encourages to use best practices.
- [ x] `pnpm run prettier` for formatting code and docs
> test: incorporate eslint-plugin-testing-library and fix reported issues

- .github/workflows/ecosystem-ci.yml
using https://github.com/jotaijs/jotai-ecosystem-ci
> add ecosystem-ci workflow

- .github/workflows/ecosystem-ci.yml
> fix(workflow): ecosystem-ci

- .github/workflows/ecosystem-ci.yml
* update .github/workflows/ecosystem-ci.yml's `actions/setup-node` version `3` to `4`(latest)
> chore(.github/workflows/ecosystem-ci.yml): update actions/setup-node version 3 to 4

- .github/workflows/compressed-size-action.yml
- .github/workflows/lint-and-type.yml
- .github/workflows/livecodes-preview.yml
- .github/workflows/publish.yml
- .github/workflows/test-multiple-builds.yml
- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
* same with https://github.com/pmndrs/zustand/pull/2893
> chore(.github/workflows): update actions/setup-node's node-version 18 to 20

- .github/workflows/compressed-size-action.yml
- .github/workflows/livecodes-preview.yml
* same with https://github.com/pmndrs/zustand/pull/2894
> chore(.github/workflows): unify format style

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
"pending" is confusing because we also use "pending promise" for a different thing.
> refactor(store): rename pending to batch

- tests/vanilla/storedev.test.tsx
> chore(test): dev store method

- .github/workflows/compressed-size-action.yml
- .github/workflows/cr.yml
- .github/workflows/ecosystem-ci.yml
- .github/workflows/lint-and-type.yml
- .github/workflows/livecodes-preview.yml
- .github/workflows/publish.yml
- .github/workflows/test-multiple-builds.yml
- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
* Same with https://github.com/pmndrs/zustand/pull/2918
> chore(.github/workflows): improve workflow with removing duplicated configs

- .github/workflows/test-multiple-versions.yml
* Same with https://github.com/pmndrs/zustand/pull/2920
> chore(.github/workflows/test-multiple-versions.yml): improve workflow with removing duplicated configs

- website/gatsby-shared.js
- website/src/components/docs.js
- website/src/components/jotai.js
- website/src/components/layout.js
- website/src/components/menu.js
- website/src/components/shelf.js
- website/src/components/sidebar.js
- website/src/components/wrapper.js
- website/src/hooks/index.js
This PR introduces the new docs menu experience.
> feat(website): docs menu

- .github/workflows/compressed-size-action.yml
- .github/workflows/cr.yml
- .github/workflows/ecosystem-ci.yml
- .github/workflows/lint-and-type.yml
- .github/workflows/livecodes-preview.yml
- .github/workflows/publish.yml
- .github/workflows/test-multiple-builds.yml
- .github/workflows/test-multiple-versions.yml
- .github/workflows/test-old-typescript.yml
* Same with https://github.com/pmndrs/zustand/pull/2933
> chore(.github/workflows): change 'node-version' to 'lts/*' in 'actions/setup-node'

- src/vanilla/store.ts
> name devStore functions

- .github/workflows/test-old-typescript.yml
- package.json
- pnpm-lock.yaml
> chore: update typescript

- docs/guides/debugging.mdx
> fix(website): repair broken images

- package.json
- pnpm-lock.yaml
- tests/vanilla/basic.test.tsx
- tests/vanilla/store.test.tsx
- tests/vanilla/storedev.test.tsx
- vitest.config.mts
To make our debugging life easier and also improve babel plugin.
> chore(tests): use babel/plugin-debug-label

- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
> fix(core): derived atom is not re-evaluated if it read between multiple set

- .github/workflows/test-multiple-builds.yml
- src/vanilla/internals.ts
- tests/vanilla/internals.test.tsx
BUILDING_BLOCKS value on store is equal to the sparse array of building blocks passed in to buildStore. Return the full buildingBlocks array instead.
> full building blocks

- package.json
- pnpm-lock.yaml
* Same with https://github.com/pmndrs/zustand/pull/3012
> chore(package.json): upgrade pnpm from v8 to v9

- src/vanilla/internals.ts
I discovered some extra code that was causing the change hook to fire an extra time for syncEffect. I haven't been able to reproduce in a test that doesn't include syncEffect. Since, readAtomState finally performs a similar check, I believe this one is redundant, but please validate this conclusion on your own.
```ts
it('should cause change hooks to fire once when effect updates the watched atom', function test() {
const countAtom = atom(0)
countAtom.debugLabel = 'watchedAtom'
const refreshAtom = atom(0)
refreshAtom.debugLabel = 'refreshAtom'
let runCount = 0
const effectAtom = atomEffect((get, set) => {
++runCount
get(refreshAtom)
get(countAtom)
set(countAtom, (v) => v + 1)
})
effectAtom.debugLabel = 'effect'
const store = createDebugStore()
const buildingBlocks = …
```
> fix(core): Remove extra onChange store hook in recomputeInvalidatedDependents

- .github/workflows/test-multiple-builds.yml
- docs/utilities/resettable.mdx
- src/vanilla/utils/atomWithRefresh.ts
- tests/vanilla/utils/atomWithRefresh.test.ts
…
https://github.com/pmndrs/jotai/discussions/2995
Fixes #
Proposed fix for the issue where passing something into the refresh function causes it to do nothing.
> fix(atomWithRefresh): non-writable refreshables throw an error if implicitly passed an argument

- package.json
* replace doule spaces with single space in `fix:format` script
> chore(package.json): replace doule spaces with single space in 'fix:format' script

- docs/extensions/effect.mdx
Simplifies website docs for jotai-effect.
> docs: simplify jotai-effect docs

- src/react/useAtomValue.ts
- src/vanilla/utils/atomWithObservable.ts
- tests/react/vanilla-utils/atomWithObservable.test.tsx
> fix(utils): atomWithObservable option for React 19 behavior

- src/react/useAtomValue.ts
- src/vanilla/internals.ts
I didn't like `onCancel` hack.
> refactor(core): avoid onCancel hack

- README.md
* Relates https://github.com/pmndrs/valtio/pull/1079
> docs(README.md): change build badge url

- docs/utilities/storage.mdx
Fixes #3054
Related to #3055 
This adds a cleanup function to the subscriber in the example for validating stored values in `atomWithStorage`.
> docs: add atomWithStorage validating stored values cleanup

- babel.config.mjs
- rollup.config.mjs
> chore(babel): migrate commonjs to esmodule

- tests/react/useAtomValue.test.tsx
Fixes #
Noticed the test coverage for useAtomValue was lacking so I thought it'll be good to add additional tests to help! Got some help with the [Takeoff](https://www.trytakeoff.ai/) vscode extension for this.
> test: additional test coverage for useAtomValue

- eslint.config.mjs
- tests/react/abortable.test.tsx
- tests/react/async.test.tsx
- tests/react/async2.test.tsx
- tests/react/basic.test.tsx
- tests/react/dependency.test.tsx
- tests/react/error.test.tsx
- tests/react/items.test.tsx
- tests/react/onmount.test.tsx
- tests/react/optimization.test.tsx
- tests/react/provider.test.tsx
- tests/react/transition.test.tsx
- tests/react/useAtomValue.test.tsx
- tests/react/useSetAtom.test.tsx
- tests/react/utils/useAtomCallback.test.tsx
- tests/react/utils/useHydrateAtoms.test.tsx
- tests/react/utils/useReducerAtom.test.tsx
- tests/react/utils/useResetAtom.test.tsx
- tests/react/vanilla-utils/atomFamily.test.tsx
- tests/react/vanilla-utils/atomWithDefault.test.tsx
- tests/react/vanilla-utils/atomWithObservable.test.tsx
- tests/react/vanilla-utils/atomWithReducer.test.tsx
- tests/react/vanilla-utils/atomWithRefresh.test.tsx
- tests/react/vanilla-utils/atomWithStorage.test.tsx
- tests/react/vanilla-utils/freezeAtom.test.tsx
- tests/react/vanilla-utils/loadable.test.tsx
- tests/react/vanilla-utils/selectAtom.test.tsx
- tests/react/vanilla-utils/splitAtom.test.tsx
Fixes #
* relate https://github.com/pmndrs/valtio/pull/1107
> test(*): add 'expect' with 'toBeInTheDocument'

- docs/basics/functional-programming-and-jotai.mdx
- docs/guides/debugging.mdx
- docs/guides/nextjs.mdx
- docs/guides/performance.mdx
- tests/vanilla/store.test.tsx
Fixes #
fix some minor issues in comments
> chore: fix some minor issues in comments

- docs/guides/react-native.mdx
- tests/react/vanilla-utils/splitAtom.test.tsx
Fixes #
fix some typos in comment
> chore: fix some typos in comment

- tests/react/transition.test.tsx
improved wording and consistency in code:
commited - committed x3
> test: minor text cleanup

- src/vanilla/atom.ts
- src/vanilla/store.ts
- tests/vanilla/store.test.tsx
Drop deprecated internal types and functions.
> breaking: drop deprecated devstore

- src/react/utils/useHydrateAtoms.ts
Supports multiple args for useHydrateAtoms hook.
> fix(utils): support multiple args for useHydrateAtoms

- eslint.config.mjs
- tests/react/transition.test.tsx
- tests/react/types.test.tsx
- tests/vanilla/store.test.tsx
- tests/vanilla/types.test.tsx
- tests/vanilla/utils/atomWithRefresh.test.ts
- tests/vanilla/utils/types.test.tsx
follow https://github.com/pmndrs/valtio/pull/1163
> chore: strict unused check

- docs/third-party/bunja.mdx
Update docs for [bunja](https://github.com/disjukr/bunja) v2
> docs: update bunja docs for v2 api changes
